// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/apis/deployment/ingressannotations.go

// Package deployment is a generated GoMock package.
package deployment

import (
	reflect "reflect"

	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	gomock "github.com/golang/mock/gomock"
)

// MockIngressAnnotations is a mock of IngressAnnotations interface.
type MockIngressAnnotations struct {
	ctrl     *gomock.Controller
	recorder *MockIngressAnnotationsMockRecorder
}

// MockIngressAnnotationsMockRecorder is the mock recorder for MockIngressAnnotations.
type MockIngressAnnotationsMockRecorder struct {
	mock *MockIngressAnnotations
}

// NewMockIngressAnnotations creates a new mock instance.
func NewMockIngressAnnotations(ctrl *gomock.Controller) *MockIngressAnnotations {
	mock := &MockIngressAnnotations{ctrl: ctrl}
	mock.recorder = &MockIngressAnnotationsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngressAnnotations) EXPECT() *MockIngressAnnotationsMockRecorder {
	return m.recorder
}

// GetAnnotations mocks base method.
func (m *MockIngressAnnotations) GetAnnotations(component v1.RadixCommonDeployComponent) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAnnotations", component)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetAnnotations indicates an expected call of GetAnnotations.
func (mr *MockIngressAnnotationsMockRecorder) GetAnnotations(component interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAnnotations", reflect.TypeOf((*MockIngressAnnotations)(nil).GetAnnotations), component)
}
