// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/apis/deployment/securitycontext.go

// Package deployment is a generated GoMock package.
package deployment

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v10 "k8s.io/api/core/v1"
)

// MockSecurityContextBuilder is a mock of SecurityContextBuilder interface.
type MockSecurityContextBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockSecurityContextBuilderMockRecorder
}

// MockSecurityContextBuilderMockRecorder is the mock recorder for MockSecurityContextBuilder.
type MockSecurityContextBuilderMockRecorder struct {
	mock *MockSecurityContextBuilder
}

// NewMockSecurityContextBuilder creates a new mock instance.
func NewMockSecurityContextBuilder(ctrl *gomock.Controller) *MockSecurityContextBuilder {
	mock := &MockSecurityContextBuilder{ctrl: ctrl}
	mock.recorder = &MockSecurityContextBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecurityContextBuilder) EXPECT() *MockSecurityContextBuilderMockRecorder {
	return m.recorder
}

// BuildContainerSecurityContext mocks base method.
func (m *MockSecurityContextBuilder) BuildContainerSecurityContext() *v10.SecurityContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildContainerSecurityContext")
	ret0, _ := ret[0].(*v10.SecurityContext)
	return ret0
}

// BuildContainerSecurityContext indicates an expected call of BuildContainerSecurityContext.
func (mr *MockSecurityContextBuilderMockRecorder) BuildContainerSecurityContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildContainerSecurityContext", reflect.TypeOf((*MockSecurityContextBuilder)(nil).BuildContainerSecurityContext))
}

// BuildPodSecurityContext mocks base method.
func (m *MockSecurityContextBuilder) BuildPodSecurityContext() *v10.PodSecurityContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildPodSecurityContext")
	ret0, _ := ret[0].(*v10.PodSecurityContext)
	return ret0
}

// BuildPodSecurityContext indicates an expected call of BuildPodSecurityContext.
func (mr *MockSecurityContextBuilderMockRecorder) BuildPodSecurityContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildPodSecurityContext", reflect.TypeOf((*MockSecurityContextBuilder)(nil).BuildPodSecurityContext))
}
