/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	radixv1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRadixDNSAliases implements RadixDNSAliasInterface
type FakeRadixDNSAliases struct {
	Fake *FakeRadixV1
}

var radixdnsaliasesResource = schema.GroupVersionResource{Group: "radix.equinor.com", Version: "v1", Resource: "radixdnsaliases"}

var radixdnsaliasesKind = schema.GroupVersionKind{Group: "radix.equinor.com", Version: "v1", Kind: "RadixDNSAlias"}

// Get takes name of the radixDNSAlias, and returns the corresponding radixDNSAlias object, and an error if there is any.
func (c *FakeRadixDNSAliases) Get(ctx context.Context, name string, options v1.GetOptions) (result *radixv1.RadixDNSAlias, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(radixdnsaliasesResource, name), &radixv1.RadixDNSAlias{})
	if obj == nil {
		return nil, err
	}
	return obj.(*radixv1.RadixDNSAlias), err
}

// List takes label and field selectors, and returns the list of RadixDNSAliases that match those selectors.
func (c *FakeRadixDNSAliases) List(ctx context.Context, opts v1.ListOptions) (result *radixv1.RadixDNSAliasList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(radixdnsaliasesResource, radixdnsaliasesKind, opts), &radixv1.RadixDNSAliasList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &radixv1.RadixDNSAliasList{ListMeta: obj.(*radixv1.RadixDNSAliasList).ListMeta}
	for _, item := range obj.(*radixv1.RadixDNSAliasList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested radixDNSAliases.
func (c *FakeRadixDNSAliases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(radixdnsaliasesResource, opts))
}

// Create takes the representation of a radixDNSAlias and creates it.  Returns the server's representation of the radixDNSAlias, and an error, if there is any.
func (c *FakeRadixDNSAliases) Create(ctx context.Context, radixDNSAlias *radixv1.RadixDNSAlias, opts v1.CreateOptions) (result *radixv1.RadixDNSAlias, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(radixdnsaliasesResource, radixDNSAlias), &radixv1.RadixDNSAlias{})
	if obj == nil {
		return nil, err
	}
	return obj.(*radixv1.RadixDNSAlias), err
}

// Update takes the representation of a radixDNSAlias and updates it. Returns the server's representation of the radixDNSAlias, and an error, if there is any.
func (c *FakeRadixDNSAliases) Update(ctx context.Context, radixDNSAlias *radixv1.RadixDNSAlias, opts v1.UpdateOptions) (result *radixv1.RadixDNSAlias, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(radixdnsaliasesResource, radixDNSAlias), &radixv1.RadixDNSAlias{})
	if obj == nil {
		return nil, err
	}
	return obj.(*radixv1.RadixDNSAlias), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRadixDNSAliases) UpdateStatus(ctx context.Context, radixDNSAlias *radixv1.RadixDNSAlias, opts v1.UpdateOptions) (*radixv1.RadixDNSAlias, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(radixdnsaliasesResource, "status", radixDNSAlias), &radixv1.RadixDNSAlias{})
	if obj == nil {
		return nil, err
	}
	return obj.(*radixv1.RadixDNSAlias), err
}

// Delete takes name of the radixDNSAlias and deletes it. Returns an error if one occurs.
func (c *FakeRadixDNSAliases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(radixdnsaliasesResource, name, opts), &radixv1.RadixDNSAlias{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRadixDNSAliases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(radixdnsaliasesResource, listOpts)

	_, err := c.Fake.Invokes(action, &radixv1.RadixDNSAliasList{})
	return err
}

// Patch applies the patch and returns the patched radixDNSAlias.
func (c *FakeRadixDNSAliases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *radixv1.RadixDNSAlias, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(radixdnsaliasesResource, name, pt, data, subresources...), &radixv1.RadixDNSAlias{})
	if obj == nil {
		return nil, err
	}
	return obj.(*radixv1.RadixDNSAlias), err
}
