/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRadixEnvironments implements RadixEnvironmentInterface
type FakeRadixEnvironments struct {
	Fake *FakeRadixV1
}

var radixenvironmentsResource = v1.SchemeGroupVersion.WithResource("radixenvironments")

var radixenvironmentsKind = v1.SchemeGroupVersion.WithKind("RadixEnvironment")

// Get takes name of the radixEnvironment, and returns the corresponding radixEnvironment object, and an error if there is any.
func (c *FakeRadixEnvironments) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RadixEnvironment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(radixenvironmentsResource, name), &v1.RadixEnvironment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RadixEnvironment), err
}

// List takes label and field selectors, and returns the list of RadixEnvironments that match those selectors.
func (c *FakeRadixEnvironments) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RadixEnvironmentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(radixenvironmentsResource, radixenvironmentsKind, opts), &v1.RadixEnvironmentList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.RadixEnvironmentList{ListMeta: obj.(*v1.RadixEnvironmentList).ListMeta}
	for _, item := range obj.(*v1.RadixEnvironmentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested radixEnvironments.
func (c *FakeRadixEnvironments) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(radixenvironmentsResource, opts))
}

// Create takes the representation of a radixEnvironment and creates it.  Returns the server's representation of the radixEnvironment, and an error, if there is any.
func (c *FakeRadixEnvironments) Create(ctx context.Context, radixEnvironment *v1.RadixEnvironment, opts metav1.CreateOptions) (result *v1.RadixEnvironment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(radixenvironmentsResource, radixEnvironment), &v1.RadixEnvironment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RadixEnvironment), err
}

// Update takes the representation of a radixEnvironment and updates it. Returns the server's representation of the radixEnvironment, and an error, if there is any.
func (c *FakeRadixEnvironments) Update(ctx context.Context, radixEnvironment *v1.RadixEnvironment, opts metav1.UpdateOptions) (result *v1.RadixEnvironment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(radixenvironmentsResource, radixEnvironment), &v1.RadixEnvironment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RadixEnvironment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRadixEnvironments) UpdateStatus(ctx context.Context, radixEnvironment *v1.RadixEnvironment, opts metav1.UpdateOptions) (*v1.RadixEnvironment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(radixenvironmentsResource, "status", radixEnvironment), &v1.RadixEnvironment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RadixEnvironment), err
}

// Delete takes name of the radixEnvironment and deletes it. Returns an error if one occurs.
func (c *FakeRadixEnvironments) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(radixenvironmentsResource, name, opts), &v1.RadixEnvironment{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRadixEnvironments) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(radixenvironmentsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.RadixEnvironmentList{})
	return err
}

// Patch applies the patch and returns the patched radixEnvironment.
func (c *FakeRadixEnvironments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RadixEnvironment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(radixenvironmentsResource, name, pt, data, subresources...), &v1.RadixEnvironment{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RadixEnvironment), err
}
