/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRadixRegistrations implements RadixRegistrationInterface
type FakeRadixRegistrations struct {
	Fake *FakeRadixV1
}

var radixregistrationsResource = v1.SchemeGroupVersion.WithResource("radixregistrations")

var radixregistrationsKind = v1.SchemeGroupVersion.WithKind("RadixRegistration")

// Get takes name of the radixRegistration, and returns the corresponding radixRegistration object, and an error if there is any.
func (c *FakeRadixRegistrations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RadixRegistration, err error) {
	emptyResult := &v1.RadixRegistration{}
	obj, err := c.Fake.
		Invokes(testing.NewRootGetActionWithOptions(radixregistrationsResource, name, options), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.RadixRegistration), err
}

// List takes label and field selectors, and returns the list of RadixRegistrations that match those selectors.
func (c *FakeRadixRegistrations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RadixRegistrationList, err error) {
	emptyResult := &v1.RadixRegistrationList{}
	obj, err := c.Fake.
		Invokes(testing.NewRootListActionWithOptions(radixregistrationsResource, radixregistrationsKind, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.RadixRegistrationList{ListMeta: obj.(*v1.RadixRegistrationList).ListMeta}
	for _, item := range obj.(*v1.RadixRegistrationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested radixRegistrations.
func (c *FakeRadixRegistrations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchActionWithOptions(radixregistrationsResource, opts))
}

// Create takes the representation of a radixRegistration and creates it.  Returns the server's representation of the radixRegistration, and an error, if there is any.
func (c *FakeRadixRegistrations) Create(ctx context.Context, radixRegistration *v1.RadixRegistration, opts metav1.CreateOptions) (result *v1.RadixRegistration, err error) {
	emptyResult := &v1.RadixRegistration{}
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateActionWithOptions(radixregistrationsResource, radixRegistration, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.RadixRegistration), err
}

// Update takes the representation of a radixRegistration and updates it. Returns the server's representation of the radixRegistration, and an error, if there is any.
func (c *FakeRadixRegistrations) Update(ctx context.Context, radixRegistration *v1.RadixRegistration, opts metav1.UpdateOptions) (result *v1.RadixRegistration, err error) {
	emptyResult := &v1.RadixRegistration{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateActionWithOptions(radixregistrationsResource, radixRegistration, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.RadixRegistration), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRadixRegistrations) UpdateStatus(ctx context.Context, radixRegistration *v1.RadixRegistration, opts metav1.UpdateOptions) (result *v1.RadixRegistration, err error) {
	emptyResult := &v1.RadixRegistration{}
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceActionWithOptions(radixregistrationsResource, "status", radixRegistration, opts), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.RadixRegistration), err
}

// Delete takes name of the radixRegistration and deletes it. Returns an error if one occurs.
func (c *FakeRadixRegistrations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(radixregistrationsResource, name, opts), &v1.RadixRegistration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRadixRegistrations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionActionWithOptions(radixregistrationsResource, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1.RadixRegistrationList{})
	return err
}

// Patch applies the patch and returns the patched radixRegistration.
func (c *FakeRadixRegistrations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RadixRegistration, err error) {
	emptyResult := &v1.RadixRegistration{}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceActionWithOptions(radixregistrationsResource, name, pt, data, opts, subresources...), emptyResult)
	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1.RadixRegistration), err
}
