package flags

const (
	LogLevel                     = "log-level"
	ConfigMapName                = "config-map-name"
	ConfigMapNamespace           = "config-map-namespace"
	AppName                      = "app-name"
	JobName                      = "job-name"
	PipelineType                 = "pipeline-type"
	Branch                       = "branch"
	GitRef                       = "git-ref"
	GitRefType                   = "git-ref-type"
	GithubWorkspace              = "github-workspace"
	CommitID                     = "commit-id"
	PromoteDeploymentName        = "promote-deployment-name"
	PromoteFromEnvironment       = "promote-from-environment"
	ToEnvironment                = "to-environment"
	RadixConfigFileName          = "radix-config-file-name"
	ImageTag                     = "image-tag"
	OverrideUseBuildCache        = "override-use-build-cache"
	RefreshBuildCache            = "refresh-build-cache"
	PushImage                    = "push-image"
	Debug                        = "debug"
	ComponentsImageTagName       = "components-image-tag-name"
	ComponentsToDeploy           = "components-to-deploy"
	ApplyConfigDeployExternalDNS = "apply-config-deploy-external-dns"
	TriggeredFromWebhook         = "triggered-from-webhook"
)
