version: "2"
linters:
  enable:
    - zerologlint
    - godox # find todos, fixmes and other markers
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "QF1008:"
      - linters:
          - staticcheck
        text: "QF1003:"
      - linters:
          - staticcheck
        text: "ST1023:"
      - linters:
          - staticcheck
        text: "QF1011:"
      - linters:
          - staticcheck
        text: "QF1001:"
      - linters:
          - godox
        text: "Line contains TODO/BUG/FIXME:"
    presets:
      - std-error-handling
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - job-scheduler/docs/docs.go
