version: "2"
linters:
  enable:
    - zerologlint
  exclusions:
    rules:
      - linters:
          - staticcheck
        text: "QF1008:"
      - linters:
          - staticcheck
        text: "QF1003:"
      - linters:
          - staticcheck
        text: "ST1023:"
      - linters:
          - staticcheck
        text: "QF1011:"
      - linters:
          - staticcheck
        text: "QF1001:"        
    presets:
      - std-error-handling
issues:
  max-same-issues: 0
formatters:
  enable:
    - gofmt
