blacklist:
  - GPL-2.0

whitelist:
  - Apache-2.0
  - BSD
  - FreeBSD
  - CC
  - ISC
  - MIT
  - MPL-2.0
  - NewBSD

exceptions:
  - github.com/pelletier/go-buffruneio  # Depends on old version which lacks a LICENSE file. Currently licensed as MIT
