# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerRegistry: 'radixdev.azurecr.io'
  azureSubscriptionEndpoint: 'radix-dev-acr'
  imageName: 'radix-operator:$(build.buildId)'
  helmDirectory: '.'

steps:
- task: Docker@1
  displayName: 'Build image'
  inputs:
    azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
    azureContainerRegistry: '$(dockerRegistry)'
    imageName: '$(dockerRegistry)/$(imageName)'
    command: build
    dockerFile: 'operator.Dockerfile'

- task: Docker@1
  displayName: 'Push image'
  inputs:
    azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
    azureContainerRegistry: '$(dockerRegistry)'
    imageName: '$(dockerRegistry)/$(imageName)'
    command: push

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'helm chart'
    targetPath: 'charts'