# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- release
- test_azdevops

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerRegistryDevSubscription: 'radixdev.azurecr.io'
  dockerRegistryProdSubscription: 'radixprod.azurecr.io'
  servicePrincipalDevSubscription: 'radix-azure-devops-dev'
  servicePrincipalProdSubscription: 'radix-azure-devops-prod'
  operatorImageName: 'radix-operator:$(build.SourceBranchName)-$(Build.SourceVersion)'
  pipelineImageName: 'radix-pipeline:$(build.SourceBranchName)-latest'

steps:
- task: Docker@1
  displayName: 'Build operator image in dev subscription'
  condition: eq(variables['Build.SourceBranchName'], 'azure-pipelines')
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalDevSubscription)'
    azureContainerRegistry: '$(dockerRegistryDevSubscription)'
    imageName: '$(dockerRegistryDevSubscription)/$(operatorImageName)'
    command: build
    dockerFile: 'operator.Dockerfile'

- task: Docker@1
  displayName: 'Push operator image in dev subscription'
  condition: eq(variables['Build.SourceBranchName'], 'azure-pipelines')
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalDevSubscription)'
    azureContainerRegistry: '$(dockerRegistryDevSubscription)'
    imageName: '$(dockerRegistryDevSubscription)/$(operatorImageName)'
    command: push

- task: Docker@1
  displayName: 'Build pipeline image in dev subscription'
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalDevSubscription)'
    azureContainerRegistry: '$(dockerRegistryDevSubscription)'
    imageName: '$(dockerRegistryDevSubscription)/$(pipelineImageName)'
    command: build
    dockerFile: 'pipeline.Dockerfile'

- task: Docker@1
  displayName: 'Push pipeline image in dev subscription'
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalDevSubscription)'
    azureContainerRegistry: '$(dockerRegistryDevSubscription)'
    imageName: '$(dockerRegistryDevSubscription)/$(pipelineImageName)'
    command: push

- task: Docker@1
  displayName: 'Build operator image in prod subscription'
  condition: eq(variables['Build.SourceBranchName'], 'test_azdevops')
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalProdSubscription)'
    azureContainerRegistry: '$(dockerRegistryProdSubscription)'
    imageName: '$(dockerRegistryProdSubscription)/$(operatorImageName)'
    command: build
    dockerFile: 'operator.Dockerfile'

- task: Docker@1
  displayName: 'Push operator image in prod subscription'
  condition: eq(variables['Build.SourceBranchName'], 'test_azdevops')
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalProdSubscription)'
    azureContainerRegistry: '$(dockerRegistryProdSubscription)'
    imageName: '$(dockerRegistryProdSubscription)/$(operatorImageName)'
    command: push

- task: Docker@1
  displayName: 'Build pipeline image in prod subscription'
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalProdSubscription)'
    azureContainerRegistry: '$(dockerRegistryProdSubscription)'
    imageName: '$(dockerRegistryProdSubscription)/$(pipelineImageName)'
    command: build
    dockerFile: 'pipeline.Dockerfile'

- task: Docker@1
  displayName: 'Push pipeline image in prod subscription'
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalProdSubscription)'
    azureContainerRegistry: '$(dockerRegistryProdSubscription)'
    imageName: '$(dockerRegistryProdSubscription)/$(pipelineImageName)'
    command: push