# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- release

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerRegistry: 'radixdev.azurecr.io'
  azureSubscriptionEndpoint: 'radix-cicd-azure-devops'
  operatorImageName: 'radix-operator:$(build.SourceBranch)-$(build.buildId)'
  pipelineImageName: 'radix-pipeline:$(build.SourceBranch)-latest'

steps:
- task: Docker@1
  displayName: 'Build operator image'
  inputs:
    azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
    azureContainerRegistry: '$(dockerRegistry)'
    imageName: '$(dockerRegistry)/$(operatorImageName)'
    command: build
    dockerFile: 'operator.Dockerfile'

- task: Docker@1
  displayName: 'Push operator image'
  inputs:
    azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
    azureContainerRegistry: '$(dockerRegistry)'
    imageName: '$(dockerRegistry)/$(operatorImageName)'
    command: push

- task: Docker@1
  displayName: 'Build pipeline image'
  inputs:
    azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
    azureContainerRegistry: '$(dockerRegistry)'
    imageName: '$(dockerRegistry)/$(pipelineImageName)'
    command: build
    dockerFile: 'pipeline.Dockerfile'

- task: Docker@1
  displayName: 'Push pipeline image'
  inputs:
    azureSubscriptionEndpoint: '$(azureSubscriptionEndpoint)'
    azureContainerRegistry: '$(dockerRegistry)'
    imageName: '$(dockerRegistry)/$(pipelineImageName)'
    command: push