# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master
- release
- test_azdevops

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  dockerRegistryDevSubscription: 'radixdev.azurecr.io'
  servicePrincipalDevSubscription: 'radix-cr-cicd-dev'
  operatorImageName: 'radix-operator:$(build.SourceBranchName)-$(build.buildId)'
  pipelineImageName: 'radix-pipeline:$(build.SourceBranchName)-latest'

steps:
- task: Docker@1
  displayName: 'Build operator image in dev subscription'
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalDevSubscription)'
    azureContainerRegistry: '$(dockerRegistryDevSubscription)'
    imageName: '$(dockerRegistryDevSubscription)/$(operatorImageName)'
    command: build
    dockerFile: 'operator.Dockerfile'

- task: Docker@1
  displayName: 'Push operator image in dev subscription'
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalDevSubscription)'
    azureContainerRegistry: '$(dockerRegistryDevSubscription)'
    imageName: '$(dockerRegistryDevSubscription)/$(operatorImageName)'
    command: push

- task: Docker@1
  displayName: 'Build pipeline image in dev subscription'
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalDevSubscription)'
    azureContainerRegistry: '$(dockerRegistryDevSubscription)'
    imageName: '$(dockerRegistryDevSubscription)/$(pipelineImageName)'
    command: build
    dockerFile: 'pipeline.Dockerfile'

- task: Docker@1
  displayName: 'Push pipeline image in dev subscription'
  inputs:
    azureSubscriptionEndpoint: '$(servicePrincipalDevSubscription)'
    azureContainerRegistry: '$(dockerRegistryDevSubscription)'
    imageName: '$(dockerRegistryDevSubscription)/$(pipelineImageName)'
    command: push