apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: radix-webhook
spec:
  environments:
  - name: prod
  components:
  - name: "webhook"
    src: "."
    dockerfileName: "webhook.Dockerfile"
    ports:
    - name: http
      port: 3001
    public: true
