apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"5"},"creationTimestamp":"2018-12-05T12:05:48Z","generation":5,"labels":{"app":"radix-operator","chart":"radix-operator-1.0.6","heritage":"Tiller","release":"radix-operator"},"name":"radix-operator","namespace":"default","resourceVersion":"1354743","selfLink":"/apis/extensions/v1beta1/namespaces/default/deployments/radix-operator","uid":"1a2ff815-f886-11e8-8f1e-962f9a2eb8ec"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"radix-operator","release":"radix-operator"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"radix-operator","release":"radix-operator"}},"spec":{"containers":[{"image":"radixdev.azurecr.io/radix-operator:OR-152_RefactorCommonCode-ad6d5537d321fddf059a21bc8ca83f3c9941ac8a","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":"metrics","scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"radix-operator","ports":[{"containerPort":9000,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/healthz","port":"metrics","scheme":"HTTP"},"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"radix-docker"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"radix-operator","serviceAccountName":"radix-operator","terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2018-12-07T12:47:41Z","lastUpdateTime":"2018-12-07T12:47:41Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2018-12-05T12:05:48Z","lastUpdateTime":"2018-12-14T08:08:12Z","message":"ReplicaSet \"radix-operator-7f789d7588\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":5,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: 2018-12-17T08:08:16Z
  generation: 1
  labels:
    app: radix-operator
    chart: radix-operator-1.0.6
    heritage: Tiller
    release: radix-operator
  name: radix-operator
  namespace: default
  resourceVersion: "1770728"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/radix-operator
  uid: e87b79a7-01d2-11e9-8f1e-962f9a2eb8ec
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: radix-operator
      release: radix-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: radix-operator
        release: radix-operator
    spec:
      containers:
      - image: radixdev.azurecr.io/radix-operator:OR-152_RefactorCommonCode-ad6d5537d321fddf059a21bc8ca83f3c9941ac8a
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: radix-operator
        ports:
        - containerPort: 9000
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: radix-docker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: radix-operator
      serviceAccountName: radix-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-12-17T08:08:20Z
    lastUpdateTime: 2018-12-17T08:08:20Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-12-17T08:08:16Z
    lastUpdateTime: 2018-12-17T08:08:20Z
    message: ReplicaSet "radix-operator-7f789d7588" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
