apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    flux.weave.works/antecedent: default:helmrelease/radix-operator
  creationTimestamp: 2019-07-02T06:21:06Z
  generation: 8
  labels:
    app: radix-operator
    chart: radix-operator-1.0.27
    heritage: Tiller
    release: radix-operator
  name: radix-operator
  namespace: default
  resourceVersion: "1690763"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/radix-operator
  uid: 935c2f9c-9c91-11e9-8cdf-eab67e50758b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: radix-operator
      release: radix-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: radix-operator
        release: radix-operator
    spec:
      containers:
      - env:
        - name: LABEL_PROMETHEUS_INSTANCE
          value: radix-stage1
        - name: DNS_ZONE
          value: dev.radix.equinor.com
        - name: APP_ALIAS_BASE_URL
          value: app.dev.radix.equinor.com
        - name: RADIXOPERATOR_CLUSTER_TYPE
          value: development
        - name: RADIXOPERATOR_DEFAULT_USER_GROUP
          value: 64b28659-4fe4-4222-8497-85dd7e43e25b
        - name: RADIXOPERATOR_APP_LIMITS_DEFAULT_MEMORY
          value: 1G
        - name: RADIXOPERATOR_APP_LIMITS_DEFAULT_CPU
          value: "1"
        - name: RADIXOPERATOR_APP_LIMITS_DEFAULT_REQUEST_MEMORY
          value: 50M
        - name: RADIXOPERATOR_APP_LIMITS_DEFAULT_REQUEST_CPU
          value: 40m
        - name: RADIXOPERATOR_APP_ENV_LIMITS_DEFAULT_MEMORY
          value: 1G
        - name: RADIXOPERATOR_APP_ENV_LIMITS_DEFAULT_CPU
          value: "1"
        - name: RADIXOPERATOR_APP_ENV_LIMITS_DEFAULT_REQUEST_MEMORY
          value: 50M
        - name: RADIXOPERATOR_APP_ENV_LIMITS_DEFAULT_REQUEST_CPU
          value: 40m
        - name: RADIXOPERATOR_APP_READINESS_PROBE_INITIAL_DELAY_SECONDS
          value: "5"
        - name: RADIXOPERATOR_APP_READINESS_PROBE_PERIOD_SECONDS
          value: "10"
        - name: RADIXOPERATOR_APP_ROLLING_UPDATE_MAX_UNAVAILABLE
          value: 25%
        - name: RADIXOPERATOR_APP_ROLLING_UPDATE_MAX_SURGE
          value: 25%
        - name: RADIX_ACTIVE_CLUSTERNAME
          value: weekly-27
        image: radixdev.azurecr.io/radix-operator:master-929883037917ce09aaf48f7f51b8a917ae1435ca
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: radix-operator
        ports:
        - containerPort: 9000
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: radix-docker
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: radix-operator
      serviceAccountName: radix-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-07-06T05:07:46Z
    lastUpdateTime: 2019-07-06T05:07:46Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-07-02T06:21:06Z
    lastUpdateTime: 2019-07-12T09:00:33Z
    message: ReplicaSet "radix-operator-78484bd74c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
