// Code generated by MockGen. DO NOT EDIT.
// Source: ./operator/batch/internal/syncerfactory.go
//
// Generated by this command:
//
//	mockgen -source ./operator/batch/internal/syncerfactory.go -destination ./operator/batch/internal/syncerfactory_mock.go -package internal
//

// Package internal is a generated GoMock package.
package internal

import (
	reflect "reflect"

	batch "github.com/equinor/radix-operator/pkg/apis/batch"
	config "github.com/equinor/radix-operator/pkg/apis/config"
	kube "github.com/equinor/radix-operator/pkg/apis/kube"
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	versioned "github.com/equinor/radix-operator/pkg/client/clientset/versioned"
	gomock "go.uber.org/mock/gomock"
	kubernetes "k8s.io/client-go/kubernetes"
)

// MockSyncerFactory is a mock of SyncerFactory interface.
type MockSyncerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSyncerFactoryMockRecorder
	isgomock struct{}
}

// MockSyncerFactoryMockRecorder is the mock recorder for MockSyncerFactory.
type MockSyncerFactoryMockRecorder struct {
	mock *MockSyncerFactory
}

// NewMockSyncerFactory creates a new mock instance.
func NewMockSyncerFactory(ctrl *gomock.Controller) *MockSyncerFactory {
	mock := &MockSyncerFactory{ctrl: ctrl}
	mock.recorder = &MockSyncerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncerFactory) EXPECT() *MockSyncerFactoryMockRecorder {
	return m.recorder
}

// CreateSyncer mocks base method.
func (m *MockSyncerFactory) CreateSyncer(kubeclient kubernetes.Interface, kubeutil *kube.Kube, radixclient versioned.Interface, registration *v1.RadixRegistration, radixBatch *v1.RadixBatch, arg5 *config.Config, options ...batch.SyncerOption) batch.Syncer {
	m.ctrl.T.Helper()
	varargs := []any{kubeclient, kubeutil, radixclient, registration, radixBatch, arg5}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSyncer", varargs...)
	ret0, _ := ret[0].(batch.Syncer)
	return ret0
}

// CreateSyncer indicates an expected call of CreateSyncer.
func (mr *MockSyncerFactoryMockRecorder) CreateSyncer(kubeclient, kubeutil, radixclient, registration, radixBatch, arg5 any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{kubeclient, kubeutil, radixclient, registration, radixBatch, arg5}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncer", reflect.TypeOf((*MockSyncerFactory)(nil).CreateSyncer), varargs...)
}
