// Code generated by MockGen. DO NOT EDIT.
// Source: ./operator/dnsalias/internal/syncerfactory.go
//
// Generated by this command:
//
//	mockgen -source ./operator/dnsalias/internal/syncerfactory.go -destination ./operator/dnsalias/internal/syncerfactory_mock.go -package internal
//

// Package internal is a generated GoMock package.
package internal

import (
	reflect "reflect"

	defaults "github.com/equinor/radix-operator/pkg/apis/defaults"
	dnsalias "github.com/equinor/radix-operator/pkg/apis/dnsalias"
	ingress "github.com/equinor/radix-operator/pkg/apis/ingress"
	kube "github.com/equinor/radix-operator/pkg/apis/kube"
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	versioned "github.com/equinor/radix-operator/pkg/client/clientset/versioned"
	gomock "go.uber.org/mock/gomock"
	kubernetes "k8s.io/client-go/kubernetes"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockSyncerFactory is a mock of SyncerFactory interface.
type MockSyncerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSyncerFactoryMockRecorder
	isgomock struct{}
}

// MockSyncerFactoryMockRecorder is the mock recorder for MockSyncerFactory.
type MockSyncerFactoryMockRecorder struct {
	mock *MockSyncerFactory
}

// NewMockSyncerFactory creates a new mock instance.
func NewMockSyncerFactory(ctrl *gomock.Controller) *MockSyncerFactory {
	mock := &MockSyncerFactory{ctrl: ctrl}
	mock.recorder = &MockSyncerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncerFactory) EXPECT() *MockSyncerFactoryMockRecorder {
	return m.recorder
}

// CreateSyncer mocks base method.
func (m *MockSyncerFactory) CreateSyncer(radixDNSAlias *v1.RadixDNSAlias, kubeClient kubernetes.Interface, kubeUtil *kube.Kube, radixClient versioned.Interface, dynamicClient client.Client, dnsZone string, oauth2Config defaults.OAuth2Config, componentIngressAnnotations, oauthIngressAnnotations, oauthProxyModeIngressAnnotation []ingress.AnnotationProvider) dnsalias.Syncer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncer", radixDNSAlias, kubeClient, kubeUtil, radixClient, dynamicClient, dnsZone, oauth2Config, componentIngressAnnotations, oauthIngressAnnotations, oauthProxyModeIngressAnnotation)
	ret0, _ := ret[0].(dnsalias.Syncer)
	return ret0
}

// CreateSyncer indicates an expected call of CreateSyncer.
func (mr *MockSyncerFactoryMockRecorder) CreateSyncer(radixDNSAlias, kubeClient, kubeUtil, radixClient, dynamicClient, dnsZone, oauth2Config, componentIngressAnnotations, oauthIngressAnnotations, oauthProxyModeIngressAnnotation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncer", reflect.TypeOf((*MockSyncerFactory)(nil).CreateSyncer), radixDNSAlias, kubeClient, kubeUtil, radixClient, dynamicClient, dnsZone, oauth2Config, componentIngressAnnotations, oauthIngressAnnotations, oauthProxyModeIngressAnnotation)
}
