/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	internalinterfaces "github.com/equinor/radix-operator/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// RadixAlerts returns a RadixAlertInformer.
	RadixAlerts() RadixAlertInformer
	// RadixApplications returns a RadixApplicationInformer.
	RadixApplications() RadixApplicationInformer
	// RadixBatches returns a RadixBatchInformer.
	RadixBatches() RadixBatchInformer
	// RadixDNSAliases returns a RadixDNSAliasInformer.
	RadixDNSAliases() RadixDNSAliasInformer
	// RadixDeployments returns a RadixDeploymentInformer.
	RadixDeployments() RadixDeploymentInformer
	// RadixEnvironments returns a RadixEnvironmentInformer.
	RadixEnvironments() RadixEnvironmentInformer
	// RadixJobs returns a RadixJobInformer.
	RadixJobs() RadixJobInformer
	// RadixRegistrations returns a RadixRegistrationInformer.
	RadixRegistrations() RadixRegistrationInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// RadixAlerts returns a RadixAlertInformer.
func (v *version) RadixAlerts() RadixAlertInformer {
	return &radixAlertInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RadixApplications returns a RadixApplicationInformer.
func (v *version) RadixApplications() RadixApplicationInformer {
	return &radixApplicationInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RadixBatches returns a RadixBatchInformer.
func (v *version) RadixBatches() RadixBatchInformer {
	return &radixBatchInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RadixDNSAliases returns a RadixDNSAliasInformer.
func (v *version) RadixDNSAliases() RadixDNSAliasInformer {
	return &radixDNSAliasInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// RadixDeployments returns a RadixDeploymentInformer.
func (v *version) RadixDeployments() RadixDeploymentInformer {
	return &radixDeploymentInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RadixEnvironments returns a RadixEnvironmentInformer.
func (v *version) RadixEnvironments() RadixEnvironmentInformer {
	return &radixEnvironmentInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}

// RadixJobs returns a RadixJobInformer.
func (v *version) RadixJobs() RadixJobInformer {
	return &radixJobInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// RadixRegistrations returns a RadixRegistrationInformer.
func (v *version) RadixRegistrations() RadixRegistrationInformer {
	return &radixRegistrationInformer{factory: v.factory, tweakListOptions: v.tweakListOptions}
}
