/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	radixv1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	versioned "github.com/equinor/radix-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/equinor/radix-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/equinor/radix-operator/pkg/client/listers/radix/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RadixDNSAliasInformer provides access to a shared informer and lister for
// RadixDNSAliases.
type RadixDNSAliasInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.RadixDNSAliasLister
}

type radixDNSAliasInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewRadixDNSAliasInformer constructs a new informer for RadixDNSAlias type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRadixDNSAliasInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRadixDNSAliasInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredRadixDNSAliasInformer constructs a new informer for RadixDNSAlias type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRadixDNSAliasInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RadixV1().RadixDNSAliases().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RadixV1().RadixDNSAliases().Watch(context.TODO(), options)
			},
		},
		&radixv1.RadixDNSAlias{},
		resyncPeriod,
		indexers,
	)
}

func (f *radixDNSAliasInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRadixDNSAliasInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *radixDNSAliasInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&radixv1.RadixDNSAlias{}, f.defaultInformer)
}

func (f *radixDNSAliasInformer) Lister() v1.RadixDNSAliasLister {
	return v1.NewRadixDNSAliasLister(f.Informer().GetIndexer())
}
