/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	internalinterfaces "pkg/client/informers/externalversions/internalinterfaces"
	time "time"

	radixv1 "./pkg/apis/radix/v1"
	versioned "./pkg/client/clientset/versioned"
	v1 "./pkg/client/listers/radix/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RadixDeploymentInformer provides access to a shared informer and lister for
// RadixDeployments.
type RadixDeploymentInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.RadixDeploymentLister
}

type radixDeploymentInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRadixDeploymentInformer constructs a new informer for RadixDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRadixDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRadixDeploymentInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRadixDeploymentInformer constructs a new informer for RadixDeployment type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRadixDeploymentInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RadixV1().RadixDeployments(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RadixV1().RadixDeployments(namespace).Watch(context.TODO(), options)
			},
		},
		&radixv1.RadixDeployment{},
		resyncPeriod,
		indexers,
	)
}

func (f *radixDeploymentInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRadixDeploymentInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *radixDeploymentInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&radixv1.RadixDeployment{}, f.defaultInformer)
}

func (f *radixDeploymentInformer) Lister() v1.RadixDeploymentLister {
	return v1.NewRadixDeploymentLister(f.Informer().GetIndexer())
}
