// Code generated by MockGen. DO NOT EDIT.
// Source: ./pipeline-runner/steps/internal/ownerreferences/owner_references.go
//
// Generated by this command:
//
//	mockgen -source ./pipeline-runner/steps/internal/ownerreferences/owner_references.go -destination ./pipeline-runner/steps/internal/ownerreferences/owner_references_mock.go -package ownerreferences
//

// Package ownerreferences is a generated GoMock package.
package ownerreferences

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MockOwnerReferenceFactory is a mock of OwnerReferenceFactory interface.
type MockOwnerReferenceFactory struct {
	ctrl     *gomock.Controller
	recorder *MockOwnerReferenceFactoryMockRecorder
	isgomock struct{}
}

// MockOwnerReferenceFactoryMockRecorder is the mock recorder for MockOwnerReferenceFactory.
type MockOwnerReferenceFactoryMockRecorder struct {
	mock *MockOwnerReferenceFactory
}

// NewMockOwnerReferenceFactory creates a new mock instance.
func NewMockOwnerReferenceFactory(ctrl *gomock.Controller) *MockOwnerReferenceFactory {
	mock := &MockOwnerReferenceFactory{ctrl: ctrl}
	mock.recorder = &MockOwnerReferenceFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOwnerReferenceFactory) EXPECT() *MockOwnerReferenceFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOwnerReferenceFactory) Create() *v1.OwnerReference {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(*v1.OwnerReference)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOwnerReferenceFactoryMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOwnerReferenceFactory)(nil).Create))
}
