/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	scheme "github.com/equinor/radix-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RadixBatchesGetter has a method to return a RadixBatchInterface.
// A group's client should implement this interface.
type RadixBatchesGetter interface {
	RadixBatches(namespace string) RadixBatchInterface
}

// RadixBatchInterface has methods to work with RadixBatch resources.
type RadixBatchInterface interface {
	Create(ctx context.Context, radixBatch *v1.RadixBatch, opts metav1.CreateOptions) (*v1.RadixBatch, error)
	Update(ctx context.Context, radixBatch *v1.RadixBatch, opts metav1.UpdateOptions) (*v1.RadixBatch, error)
	UpdateStatus(ctx context.Context, radixBatch *v1.RadixBatch, opts metav1.UpdateOptions) (*v1.RadixBatch, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.RadixBatch, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.RadixBatchList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RadixBatch, err error)
	RadixBatchExpansion
}

// radixBatches implements RadixBatchInterface
type radixBatches struct {
	client rest.Interface
	ns     string
}

// newRadixBatches returns a RadixBatches
func newRadixBatches(c *RadixV1Client, namespace string) *radixBatches {
	return &radixBatches{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the radixBatch, and returns the corresponding radixBatch object, and an error if there is any.
func (c *radixBatches) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RadixBatch, err error) {
	result = &v1.RadixBatch{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("radixbatches").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RadixBatches that match those selectors.
func (c *radixBatches) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RadixBatchList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.RadixBatchList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("radixbatches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested radixBatches.
func (c *radixBatches) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("radixbatches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a radixBatch and creates it.  Returns the server's representation of the radixBatch, and an error, if there is any.
func (c *radixBatches) Create(ctx context.Context, radixBatch *v1.RadixBatch, opts metav1.CreateOptions) (result *v1.RadixBatch, err error) {
	result = &v1.RadixBatch{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("radixbatches").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(radixBatch).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a radixBatch and updates it. Returns the server's representation of the radixBatch, and an error, if there is any.
func (c *radixBatches) Update(ctx context.Context, radixBatch *v1.RadixBatch, opts metav1.UpdateOptions) (result *v1.RadixBatch, err error) {
	result = &v1.RadixBatch{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("radixbatches").
		Name(radixBatch.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(radixBatch).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *radixBatches) UpdateStatus(ctx context.Context, radixBatch *v1.RadixBatch, opts metav1.UpdateOptions) (result *v1.RadixBatch, err error) {
	result = &v1.RadixBatch{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("radixbatches").
		Name(radixBatch.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(radixBatch).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the radixBatch and deletes it. Returns an error if one occurs.
func (c *radixBatches) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("radixbatches").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *radixBatches) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("radixbatches").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched radixBatch.
func (c *radixBatches) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RadixBatch, err error) {
	result = &v1.RadixBatch{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("radixbatches").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
