/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"

	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	scheme "github.com/equinor/radix-operator/pkg/client/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RadixBatchesGetter has a method to return a RadixBatchInterface.
// A group's client should implement this interface.
type RadixBatchesGetter interface {
	RadixBatches(namespace string) RadixBatchInterface
}

// RadixBatchInterface has methods to work with RadixBatch resources.
type RadixBatchInterface interface {
	Create(ctx context.Context, radixBatch *v1.RadixBatch, opts metav1.CreateOptions) (*v1.RadixBatch, error)
	Update(ctx context.Context, radixBatch *v1.RadixBatch, opts metav1.UpdateOptions) (*v1.RadixBatch, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, radixBatch *v1.RadixBatch, opts metav1.UpdateOptions) (*v1.RadixBatch, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.RadixBatch, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.RadixBatchList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RadixBatch, err error)
	RadixBatchExpansion
}

// radixBatches implements RadixBatchInterface
type radixBatches struct {
	*gentype.ClientWithList[*v1.RadixBatch, *v1.RadixBatchList]
}

// newRadixBatches returns a RadixBatches
func newRadixBatches(c *RadixV1Client, namespace string) *radixBatches {
	return &radixBatches{
		gentype.NewClientWithList[*v1.RadixBatch, *v1.RadixBatchList](
			"radixbatches",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1.RadixBatch { return &v1.RadixBatch{} },
			func() *v1.RadixBatchList { return &v1.RadixBatchList{} }),
	}
}
