spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  automountServiceAccountToken: false
  containers:
    - name: "proxy"
      image: "quay.io/oauth2-proxy/oauth2-proxy:latest"
      imagePullPolicy: "Always"
      ports:
        - containerPort: 4180
      readinessProbe:
        failureThreshold: 3
        initialDelaySeconds: 5
        periodSeconds: 10
        successThreshold: 1
        tcpSocket:
          port: 4180
        timeoutSeconds: 1
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1001
        seccompProfile:
          type: RuntimeDefault
      resources:
        limits:
          memory: 100M
        requests:
          cpu: 10m
          memory: 100M
