# File where to store auto increments                                          
version_file := ".buildver"
BLD_FILE ?= $(version_file)


# Prepare callable function. This function updates BLD_FILE
currentver := $(shell cat ${BLD_FILE})
major := $(shell echo $(currentver) | cut -d. -f1)
minor := $(shell echo $(currentver) | cut -d. -f2)
oldrevision := $(shell echo $(currentver) | cut -d. -f3)
revision := $(shell expr $(oldrevision) + 1)

define buildver
    $(shell echo "$(major).$(minor).$(revision)" > $(BLD_FILE))
endef