// Code generated by MockGen. DO NOT EDIT.
// Source: ./radix-operator/job/handler.go

// Package job is a generated GoMock package.
package job

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	record "k8s.io/client-go/tools/record"
)

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// CleanupJobHistory mocks base method.
func (m *MockHandler) CleanupJobHistory(ctx context.Context, appName string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CleanupJobHistory", ctx, appName)
}

// CleanupJobHistory indicates an expected call of CleanupJobHistory.
func (mr *MockHandlerMockRecorder) CleanupJobHistory(ctx, radixJob interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupJobHistory", reflect.TypeOf((*MockHandler)(nil).CleanupJobHistory), ctx, radixJob)
}

// Sync mocks base method.
func (m *MockHandler) Sync(ctx context.Context, namespace, name string, eventRecorder record.EventRecorder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sync", ctx, namespace, name, eventRecorder)
	ret0, _ := ret[0].(error)
	return ret0
}

// Sync indicates an expected call of Sync.
func (mr *MockHandlerMockRecorder) Sync(ctx, namespace, name, eventRecorder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sync", reflect.TypeOf((*MockHandler)(nil).Sync), ctx, namespace, name, eventRecorder)
}
