/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// RadixAlertListerExpansion allows custom methods to be added to
// RadixAlertLister.
type RadixAlertListerExpansion interface{}

// RadixAlertNamespaceListerExpansion allows custom methods to be added to
// RadixAlertNamespaceLister.
type RadixAlertNamespaceListerExpansion interface{}

// RadixApplicationListerExpansion allows custom methods to be added to
// RadixApplicationLister.
type RadixApplicationListerExpansion interface{}

// RadixApplicationNamespaceListerExpansion allows custom methods to be added to
// RadixApplicationNamespaceLister.
type RadixApplicationNamespaceListerExpansion interface{}

// RadixBatchListerExpansion allows custom methods to be added to
// RadixBatchLister.
type RadixBatchListerExpansion interface{}

// RadixBatchNamespaceListerExpansion allows custom methods to be added to
// RadixBatchNamespaceLister.
type RadixBatchNamespaceListerExpansion interface{}

// RadixDNSAliasListerExpansion allows custom methods to be added to
// RadixDNSAliasLister.
type RadixDNSAliasListerExpansion interface{}

// RadixDeploymentListerExpansion allows custom methods to be added to
// RadixDeploymentLister.
type RadixDeploymentListerExpansion interface{}

// RadixDeploymentNamespaceListerExpansion allows custom methods to be added to
// RadixDeploymentNamespaceLister.
type RadixDeploymentNamespaceListerExpansion interface{}

// RadixEnvironmentListerExpansion allows custom methods to be added to
// RadixEnvironmentLister.
type RadixEnvironmentListerExpansion interface{}

// RadixJobListerExpansion allows custom methods to be added to
// RadixJobLister.
type RadixJobListerExpansion interface{}

// RadixJobNamespaceListerExpansion allows custom methods to be added to
// RadixJobNamespaceLister.
type RadixJobNamespaceListerExpansion interface{}

// RadixRegistrationListerExpansion allows custom methods to be added to
// RadixRegistrationLister.
type RadixRegistrationListerExpansion interface{}
