/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// RadixAlertListerExpansion allows custom methods to be added to
// RadixAlertLister.
type RadixAlertListerExpansion interface{}

// RadixAlertNamespaceListerExpansion allows custom methods to be added to
// RadixAlertNamespaceLister.
type RadixAlertNamespaceListerExpansion interface{}

// RadixApplicationListerExpansion allows custom methods to be added to
// RadixApplicationLister.
type RadixApplicationListerExpansion interface{}

// RadixApplicationNamespaceListerExpansion allows custom methods to be added to
// RadixApplicationNamespaceLister.
type RadixApplicationNamespaceListerExpansion interface{}

// RadixBatchListerExpansion allows custom methods to be added to
// RadixBatchLister.
type RadixBatchListerExpansion interface{}

// RadixBatchNamespaceListerExpansion allows custom methods to be added to
// RadixBatchNamespaceLister.
type RadixBatchNamespaceListerExpansion interface{}

// RadixDNSAliasListerExpansion allows custom methods to be added to
// RadixDNSAliasLister.
type RadixDNSAliasListerExpansion interface{}

// RadixDeploymentListerExpansion allows custom methods to be added to
// RadixDeploymentLister.
type RadixDeploymentListerExpansion interface{}

// RadixDeploymentNamespaceListerExpansion allows custom methods to be added to
// RadixDeploymentNamespaceLister.
type RadixDeploymentNamespaceListerExpansion interface{}

// RadixEnvironmentListerExpansion allows custom methods to be added to
// RadixEnvironmentLister.
type RadixEnvironmentListerExpansion interface{}

// RadixJobListerExpansion allows custom methods to be added to
// RadixJobLister.
type RadixJobListerExpansion interface{}

// RadixJobNamespaceListerExpansion allows custom methods to be added to
// RadixJobNamespaceLister.
type RadixJobNamespaceListerExpansion interface{}

// RadixRegistrationListerExpansion allows custom methods to be added to
// RadixRegistrationLister.
type RadixRegistrationListerExpansion interface{}
