/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RadixApplicationLister helps list RadixApplications.
// All objects returned here must be treated as read-only.
type RadixApplicationLister interface {
	// List lists all RadixApplications in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RadixApplication, err error)
	// RadixApplications returns an object that can list and get RadixApplications.
	RadixApplications(namespace string) RadixApplicationNamespaceLister
	RadixApplicationListerExpansion
}

// radixApplicationLister implements the RadixApplicationLister interface.
type radixApplicationLister struct {
	indexer cache.Indexer
}

// NewRadixApplicationLister returns a new RadixApplicationLister.
func NewRadixApplicationLister(indexer cache.Indexer) RadixApplicationLister {
	return &radixApplicationLister{indexer: indexer}
}

// List lists all RadixApplications in the indexer.
func (s *radixApplicationLister) List(selector labels.Selector) (ret []*v1.RadixApplication, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.RadixApplication))
	})
	return ret, err
}

// RadixApplications returns an object that can list and get RadixApplications.
func (s *radixApplicationLister) RadixApplications(namespace string) RadixApplicationNamespaceLister {
	return radixApplicationNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RadixApplicationNamespaceLister helps list and get RadixApplications.
// All objects returned here must be treated as read-only.
type RadixApplicationNamespaceLister interface {
	// List lists all RadixApplications in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RadixApplication, err error)
	// Get retrieves the RadixApplication from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.RadixApplication, error)
	RadixApplicationNamespaceListerExpansion
}

// radixApplicationNamespaceLister implements the RadixApplicationNamespaceLister
// interface.
type radixApplicationNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RadixApplications in the indexer for a given namespace.
func (s radixApplicationNamespaceLister) List(selector labels.Selector) (ret []*v1.RadixApplication, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.RadixApplication))
	})
	return ret, err
}

// Get retrieves the RadixApplication from the indexer for a given namespace and name.
func (s radixApplicationNamespaceLister) Get(name string) (*v1.RadixApplication, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("radixapplication"), name)
	}
	return obj.(*v1.RadixApplication), nil
}
