/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// RadixDNSAliasLister helps list RadixDNSAliases.
// All objects returned here must be treated as read-only.
type RadixDNSAliasLister interface {
	// List lists all RadixDNSAliases in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RadixDNSAlias, err error)
	// Get retrieves the RadixDNSAlias from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.RadixDNSAlias, error)
	RadixDNSAliasListerExpansion
}

// radixDNSAliasLister implements the RadixDNSAliasLister interface.
type radixDNSAliasLister struct {
	listers.ResourceIndexer[*v1.RadixDNSAlias]
}

// NewRadixDNSAliasLister returns a new RadixDNSAliasLister.
func NewRadixDNSAliasLister(indexer cache.Indexer) RadixDNSAliasLister {
	return &radixDNSAliasLister{listers.New[*v1.RadixDNSAlias](indexer, v1.Resource("radixdnsalias"))}
}
