/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// RadixJobLister helps list RadixJobs.
// All objects returned here must be treated as read-only.
type RadixJobLister interface {
	// List lists all RadixJobs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RadixJob, err error)
	// RadixJobs returns an object that can list and get RadixJobs.
	RadixJobs(namespace string) RadixJobNamespaceLister
	RadixJobListerExpansion
}

// radixJobLister implements the RadixJobLister interface.
type radixJobLister struct {
	indexer cache.Indexer
}

// NewRadixJobLister returns a new RadixJobLister.
func NewRadixJobLister(indexer cache.Indexer) RadixJobLister {
	return &radixJobLister{indexer: indexer}
}

// List lists all RadixJobs in the indexer.
func (s *radixJobLister) List(selector labels.Selector) (ret []*v1.RadixJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.RadixJob))
	})
	return ret, err
}

// RadixJobs returns an object that can list and get RadixJobs.
func (s *radixJobLister) RadixJobs(namespace string) RadixJobNamespaceLister {
	return radixJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// RadixJobNamespaceLister helps list and get RadixJobs.
// All objects returned here must be treated as read-only.
type RadixJobNamespaceLister interface {
	// List lists all RadixJobs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RadixJob, err error)
	// Get retrieves the RadixJob from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.RadixJob, error)
	RadixJobNamespaceListerExpansion
}

// radixJobNamespaceLister implements the RadixJobNamespaceLister
// interface.
type radixJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all RadixJobs in the indexer for a given namespace.
func (s radixJobNamespaceLister) List(selector labels.Selector) (ret []*v1.RadixJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1.RadixJob))
	})
	return ret, err
}

// Get retrieves the RadixJob from the indexer for a given namespace and name.
func (s radixJobNamespaceLister) Get(name string) (*v1.RadixJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1.Resource("radixjob"), name)
	}
	return obj.(*v1.RadixJob), nil
}
