/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// RadixAlertLister helps list RadixAlerts.
// All objects returned here must be treated as read-only.
type RadixAlertLister interface {
	// List lists all RadixAlerts in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RadixAlert, err error)
	// RadixAlerts returns an object that can list and get RadixAlerts.
	RadixAlerts(namespace string) RadixAlertNamespaceLister
	RadixAlertListerExpansion
}

// radixAlertLister implements the RadixAlertLister interface.
type radixAlertLister struct {
	listers.ResourceIndexer[*v1.RadixAlert]
}

// NewRadixAlertLister returns a new RadixAlertLister.
func NewRadixAlertLister(indexer cache.Indexer) RadixAlertLister {
	return &radixAlertLister{listers.New[*v1.RadixAlert](indexer, v1.Resource("radixalert"))}
}

// RadixAlerts returns an object that can list and get RadixAlerts.
func (s *radixAlertLister) RadixAlerts(namespace string) RadixAlertNamespaceLister {
	return radixAlertNamespaceLister{listers.NewNamespaced[*v1.RadixAlert](s.ResourceIndexer, namespace)}
}

// RadixAlertNamespaceLister helps list and get RadixAlerts.
// All objects returned here must be treated as read-only.
type RadixAlertNamespaceLister interface {
	// List lists all RadixAlerts in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RadixAlert, err error)
	// Get retrieves the RadixAlert from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.RadixAlert, error)
	RadixAlertNamespaceListerExpansion
}

// radixAlertNamespaceLister implements the RadixAlertNamespaceLister
// interface.
type radixAlertNamespaceLister struct {
	listers.ResourceIndexer[*v1.RadixAlert]
}
