/*
MIT License

Copyright (c) 2024 Equinor

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// RadixDeploymentLister helps list RadixDeployments.
// All objects returned here must be treated as read-only.
type RadixDeploymentLister interface {
	// List lists all RadixDeployments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RadixDeployment, err error)
	// RadixDeployments returns an object that can list and get RadixDeployments.
	RadixDeployments(namespace string) RadixDeploymentNamespaceLister
	RadixDeploymentListerExpansion
}

// radixDeploymentLister implements the RadixDeploymentLister interface.
type radixDeploymentLister struct {
	listers.ResourceIndexer[*v1.RadixDeployment]
}

// NewRadixDeploymentLister returns a new RadixDeploymentLister.
func NewRadixDeploymentLister(indexer cache.Indexer) RadixDeploymentLister {
	return &radixDeploymentLister{listers.New[*v1.RadixDeployment](indexer, v1.Resource("radixdeployment"))}
}

// RadixDeployments returns an object that can list and get RadixDeployments.
func (s *radixDeploymentLister) RadixDeployments(namespace string) RadixDeploymentNamespaceLister {
	return radixDeploymentNamespaceLister{listers.NewNamespaced[*v1.RadixDeployment](s.ResourceIndexer, namespace)}
}

// RadixDeploymentNamespaceLister helps list and get RadixDeployments.
// All objects returned here must be treated as read-only.
type RadixDeploymentNamespaceLister interface {
	// List lists all RadixDeployments in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1.RadixDeployment, err error)
	// Get retrieves the RadixDeployment from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1.RadixDeployment, error)
	RadixDeploymentNamespaceListerExpansion
}

// radixDeploymentNamespaceLister implements the RadixDeploymentNamespaceLister
// interface.
type radixDeploymentNamespaceLister struct {
	listers.ResourceIndexer[*v1.RadixDeployment]
}
