// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/environments/job_handler.go
//
// Generated by this command:
//
//	mockgen -source ./api/environments/job_handler.go -destination ./api/environments/mock/job_handler_mock.go -package mock
//

// Package mock is a generated GoMock package.
package mock
