// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/apis/alert/alertfactory.go
//
// Generated by this command:
//
//	mockgen -source ./pkg/apis/alert/alertfactory.go -destination ./pkg/apis/alert/alertfactory_mock.go -package alert
//

// Package alert is a generated GoMock package.
package alert

import (
	reflect "reflect"

	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	gomock "go.uber.org/mock/gomock"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// MockAlertSyncerFactory is a mock of AlertSyncerFactory interface.
type MockAlertSyncerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAlertSyncerFactoryMockRecorder
	isgomock struct{}
}

// MockAlertSyncerFactoryMockRecorder is the mock recorder for MockAlertSyncerFactory.
type MockAlertSyncerFactoryMockRecorder struct {
	mock *MockAlertSyncerFactory
}

// NewMockAlertSyncerFactory creates a new mock instance.
func NewMockAlertSyncerFactory(ctrl *gomock.Controller) *MockAlertSyncerFactory {
	mock := &MockAlertSyncerFactory{ctrl: ctrl}
	mock.recorder = &MockAlertSyncerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertSyncerFactory) EXPECT() *MockAlertSyncerFactoryMockRecorder {
	return m.recorder
}

// CreateAlertSyncer mocks base method.
func (m *MockAlertSyncerFactory) CreateAlertSyncer(dynamicClient client.Client, radixAlert *v1.RadixAlert) AlertSyncer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlertSyncer", dynamicClient, radixAlert)
	ret0, _ := ret[0].(AlertSyncer)
	return ret0
}

// CreateAlertSyncer indicates an expected call of CreateAlertSyncer.
func (mr *MockAlertSyncerFactoryMockRecorder) CreateAlertSyncer(dynamicClient, radixAlert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlertSyncer", reflect.TypeOf((*MockAlertSyncerFactory)(nil).CreateAlertSyncer), dynamicClient, radixAlert)
}
