// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/apis/alert/alertfactory.go

// Package alert is a generated GoMock package.
package alert

import (
	reflect "reflect"

	kube "github.com/equinor/radix-operator/pkg/apis/kube"
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	versioned "github.com/equinor/radix-operator/pkg/client/clientset/versioned"
	gomock "github.com/golang/mock/gomock"
	versioned0 "github.com/prometheus-operator/prometheus-operator/pkg/client/versioned"
	kubernetes "k8s.io/client-go/kubernetes"
)

// MockAlertSyncerFactory is a mock of AlertSyncerFactory interface.
type MockAlertSyncerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockAlertSyncerFactoryMockRecorder
}

// MockAlertSyncerFactoryMockRecorder is the mock recorder for MockAlertSyncerFactory.
type MockAlertSyncerFactoryMockRecorder struct {
	mock *MockAlertSyncerFactory
}

// NewMockAlertSyncerFactory creates a new mock instance.
func NewMockAlertSyncerFactory(ctrl *gomock.Controller) *MockAlertSyncerFactory {
	mock := &MockAlertSyncerFactory{ctrl: ctrl}
	mock.recorder = &MockAlertSyncerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlertSyncerFactory) EXPECT() *MockAlertSyncerFactoryMockRecorder {
	return m.recorder
}

// CreateAlertSyncer mocks base method.
func (m *MockAlertSyncerFactory) CreateAlertSyncer(kubeclient kubernetes.Interface, kubeutil *kube.Kube, radixclient versioned.Interface, prometheusperatorclient versioned0.Interface, radixAlert *v1.RadixAlert) AlertSyncer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAlertSyncer", kubeclient, kubeutil, radixclient, prometheusperatorclient, radixAlert)
	ret0, _ := ret[0].(AlertSyncer)
	return ret0
}

// CreateAlertSyncer indicates an expected call of CreateAlertSyncer.
func (mr *MockAlertSyncerFactoryMockRecorder) CreateAlertSyncer(kubeclient, kubeutil, radixclient, prometheusperatorclient, radixAlert interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAlertSyncer", reflect.TypeOf((*MockAlertSyncerFactory)(nil).CreateAlertSyncer), kubeclient, kubeutil, radixclient, prometheusperatorclient, radixAlert)
}
