package radixapplication

import (
	"errors"
)

var (
	ErrUnknownServerError                          = errors.New("server error, please try again later")
	ErrNoRadixApplication                          = errors.New("no corresponding radix application found. Name of the application in radixconfig.yaml needs to be exactly the same as used when defining the app in the console")
	ErrDNSAliasComponentIsNotMarkedAsPublic        = errors.New("component for dns alias is not marked as public")
	ErrDNSAliasAlreadyUsedByAnotherApplication     = errors.New("dns alias is already used by another application")
	ErrDNSAliasReservedForRadixPlatformApplication = errors.New("dns alias is reserved for Radix platform application")
	ErrDNSAliasReservedForRadixPlatformService     = errors.New("dns alias is reserved for Radix platform service")
	ErrDNSAliasEnvironmentNotDefined               = errors.New("environment for dns alias is not defined in radix application")
	ErrDNSAliasComponentNotDefinedOrDisabled       = errors.New("component for dns alias is not defined or disabled in radix application")
	ErrExternalAliasCannotBeEmpty                  = errors.New("external alias cannot be empty")

	ErrExternalAliasEnvironmentNotDefined      = errors.New("environment for external alias is not defined in radix application")
	ErrExternalAliasComponentNotDefined        = errors.New("component for external alias is not defined or not enabled in radix application")
	ErrExternalAliasComponentNotMarkedAsPublic = errors.New("component for external alias is not marked as public")
	ErrRequestedResourceExceedsLimit           = errors.New("requested resource exceeds defined limit")
	ErrPublicPortNotFound                      = errors.New("public port not found in component ports")
	ErrMonitoringNamedPortNotFound             = errors.New("monitoring named port not found in component ports")
	ErrMonitoringNoPortsDefined                = errors.New("no ports defined for component with monitoring enabled")

	// OAuth validation errors
	ErrOAuthClientIdEmpty                                     = errors.New("oauth2 clientId cannot be empty")
	ErrOAuthRequiresPublicPort                                = errors.New("oauth2 requires component to have a public port")
	ErrOAuthProxyPrefixEmpty                                  = errors.New("oauth2 proxyPrefix cannot be empty")
	ErrOAuthProxyPrefixIsRoot                                 = errors.New("oauth2 proxyPrefix cannot be root path '/'")
	ErrOAuthSessionStoreTypeInvalid                           = errors.New("oauth2 sessionStoreType is invalid")
	ErrOAuthRedisStoreEmpty                                   = errors.New("oauth2 redisStore cannot be empty when sessionStoreType is redis")
	ErrOAuthRedisStoreConnectionURLEmpty                      = errors.New("oauth2 redisStore connectionURL cannot be empty")
	ErrOAuthOidcEmpty                                         = errors.New("oauth2 oidc configuration cannot be empty")
	ErrOAuthOidcSkipDiscoveryEmpty                            = errors.New("oauth2 oidc skipDiscovery cannot be empty")
	ErrOAuthOidcJwksUrlEmpty                                  = errors.New("oauth2 oidc jwksUrl cannot be empty when skipDiscovery is true")
	ErrOAuthLoginUrlEmpty                                     = errors.New("oauth2 loginUrl cannot be empty when oidc skipDiscovery is true")
	ErrOAuthRedeemUrlEmpty                                    = errors.New("oauth2 redeemUrl cannot be empty when oidc skipDiscovery is true")
	ErrOAuthCookieEmpty                                       = errors.New("oauth2 cookie configuration cannot be empty")
	ErrOAuthCookieNameEmpty                                   = errors.New("oauth2 cookie name cannot be empty")
	ErrOAuthCookieSameSiteInvalid                             = errors.New("oauth2 cookie sameSite is invalid")
	ErrOAuthCookieExpireInvalid                               = errors.New("oauth2 cookie expire is invalid or negative")
	ErrOAuthCookieRefreshInvalid                              = errors.New("oauth2 cookie refresh is invalid or negative")
	ErrOAuthCookieRefreshMustBeLessThanExpire                 = errors.New("oauth2 cookie refresh must be less than expire")
	ErrOAuthCookieStoreMinimalIncorrectCookieRefreshInterval  = errors.New("oauth2 cookie refresh must be 0 when cookieStore minimal is true")
	ErrOAuthCookieStoreMinimalIncorrectSetXAuthRequestHeaders = errors.New("oauth2 setXAuthRequestHeaders must be false when cookieStore minimal is true")
	ErrOAuthCookieStoreMinimalIncorrectSetAuthorizationHeader = errors.New("oauth2 setAuthorizationHeader must be false when cookieStore minimal is true")
	ErrOAuthSkipAuthRoutesInvalid                             = errors.New("oauth2 skipAuthRoutes contains invalid route")
	ErrInvalidVerificationType                                = errors.New("invalid verification type")
)
