apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: "radix-operator"
  labels:
    app: "radix-operator"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "radix-operator"
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: "radix-operator"
        release: {{ .Release.Name }}
    spec:
      serviceAccount: "radix-operator"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageCredentials.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
          resources:
            {{- toYaml .Values.resources | indent 12 -}}

      {{ if .Values.imageCredentials.registry }}
      imagePullSecrets:
        - name: {{.Values.imageCredentials.registry}}
      {{ end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}