apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    app: {{ template "radix-operator.name" . }}
    chart: {{ template "radix-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "radix-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "radix-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccount: {{ template "radix-operator.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.imageCredentials.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
          env:
            - name: KUBERNETES_PORT_443_TCP_ADDR
              value: {{ .Values.clusterFQDN }}
            - name: KUBERNETES_PORT
              value: "tcp://{{ .Values.clusterFQDN }}:443"
            - name: KUBERNETES_PORT_443_TCP
              value: "tcp://{{ .Values.clusterFQDN }}:443"
            - name: KUBERNETES_SERVICE_HOST
              value: {{ .Values.clusterFQDN }}
          resources:
            {{- toYaml .Values.resources | indent 12 -}}

      {{ if .Values.imageCredentials.registry }}
      imagePullSecrets:
        - name: {{.Values.imageCredentials.registry}}
      {{ end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{ toYaml . | indent 8 }}
      {{- end }}