apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "radix-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "radix-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "radix-operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "radix-operator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ template "radix-operator.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          env:
            - name: LABEL_PROMETHEUS_INSTANCE
              value: {{ .Values.prometheusName }}
            - name: DNS_ZONE
              value: {{ .Values.dnsZone }}
            - name: RADIX_ZONE
              value: {{ .Values.radixZone }}
            - name: APP_ALIAS_BASE_URL
              value: {{ .Values.appAliasBaseURL }}
            - name: RADIXOPERATOR_CLUSTER_TYPE
              value: {{ .Values.clusterType }}
            {{if eq .Values.clusterType "playground"}}
            - name: RADIXOPERATOR_DEFAULT_USER_GROUP
              value: "{{ .Values.radixGroups.playground }}"
            {{else}}
            - name: RADIXOPERATOR_DEFAULT_USER_GROUP
              value: "{{ .Values.radixGroups.user }}"
            {{end}}
            # For configuring limit ranges on app namespaces
            - name: RADIXOPERATOR_APP_LIMITS_DEFAULT_MEMORY
              value: {{ .Values.app.limitrange.default.memory | quote }}
            - name: RADIXOPERATOR_APP_LIMITS_DEFAULT_REQUEST_MEMORY
              value: {{ .Values.app.limitrange.defaultRequest.memory | quote }}
            - name: RADIXOPERATOR_APP_LIMITS_DEFAULT_REQUEST_CPU
              value: {{ .Values.app.limitrange.defaultRequest.cpu | quote }}
            # For configuring limit ranges on env namespaces
            - name: RADIXOPERATOR_APP_ENV_LIMITS_DEFAULT_MEMORY
              value: {{ .Values.app.env.limitrange.default.memory | quote }}
            - name: RADIXOPERATOR_APP_ENV_LIMITS_DEFAULT_REQUEST_MEMORY
              value: {{ .Values.app.env.limitrange.defaultRequest.memory | quote }}
            - name: RADIXOPERATOR_APP_ENV_LIMITS_DEFAULT_REQUEST_CPU
              value: {{ .Values.app.env.limitrange.defaultRequest.cpu | quote }}
            # For configuring limit ranges on app namespaces
            - name: RADIXOPERATOR_APP_BUILDER_RESOURCES_LIMITS_MEMORY
              value: {{ .Values.app.builder.resources.limits.memory | quote }}
            - name: RADIXOPERATOR_APP_BUILDER_RESOURCES_REQUESTS_MEMORY
              value: {{ .Values.app.builder.resources.requests.memory | quote }}
            - name: RADIXOPERATOR_APP_BUILDER_RESOURCES_REQUESTS_CPU
              value: {{ .Values.app.builder.resources.requests.cpu | quote }}
            # For configuring readiness probe
            - name: RADIXOPERATOR_APP_READINESS_PROBE_INITIAL_DELAY_SECONDS
              value: {{ .Values.app.readinessProbe.initialDelaySeconds | quote }}
            - name: RADIXOPERATOR_APP_READINESS_PROBE_PERIOD_SECONDS
              value: {{ .Values.app.readinessProbe.periodSeconds | quote }}
            # For configuring rolling update
            - name: RADIXOPERATOR_APP_ROLLING_UPDATE_MAX_UNAVAILABLE
              value: {{ .Values.app.rollingUpdate.maxUnavailable | quote }}
            - name: RADIXOPERATOR_APP_ROLLING_UPDATE_MAX_SURGE
              value: {{ .Values.app.rollingUpdate.maxSurge | quote }}
            # Active cluster name
            - name: RADIX_ACTIVE_CLUSTERNAME
              value: {{ .Values.activeClusterName }}
            # Maximum custom resources
            - name: RADIX_DEPLOYMENTS_PER_ENVIRONMENT_HISTORY_LIMIT
              value: {{ .Values.deploymentsPerEnvironmentHistoryLimit | quote }}
            - name: RADIX_PIPELINE_JOBS_HISTORY_LIMIT
              value: {{ .Values.pipelineJobsHistoryLimit | quote }}
            - name: RADIX_PIPELINE_JOBS_HISTORY_PERIOD_LIMIT
              value: {{ .Values.pipelineJobsHistoryPeriodLimit | quote }}
            - name: RADIX_TEKTON_IMAGE
              value: {{ .Values.radixTekton }}
            - name: RADIX_IMAGE_BUILDER
              value: {{ .Values.imageBuilder }}
            - name: RADIXOPERATOR_JOB_SCHEDULER
              value: {{ .Values.jobScheduler }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: LOG_PRETTY
              value: {{ .Values.logPretty | quote }}
            - name: RADIX_CONTAINER_REGISTRY
              value: {{ .Values.containerRegistry }}
            - name: RADIX_APP_CONTAINER_REGISTRY
              value: {{ .Values.appContainerRegistry }}
            - name: RADIXOPERATOR_TENANT_ID
              value: {{ .Values.tenantId }}
            - name: RADIX_OAUTH_PROXY_DEFAULT_OIDC_ISSUER_URL
              value: {{ .Values.oauthProxyDefaultIssuerUrl }}
            - name: RADIX_OAUTH_PROXY_IMAGE
              value: {{ .Values.oauthProxyImage }}
            - name: REGISTRATION_CONTROLLER_THREADS
              value: {{ .Values.registrationControllerThreads | quote }}
            - name: APPLICATION_CONTROLLER_THREADS
              value: {{ .Values.applicationControllerThreads | quote }}
            - name: ENVIRONMENT_CONTROLLER_THREADS
              value: {{ .Values.environmentControllerThreads | quote }}
            - name: DEPLOYMENT_CONTROLLER_THREADS
              value: {{ .Values.deploymentControllerThreads | quote }}
            - name: JOB_CONTROLLER_THREADS
              value: {{ .Values.jobControllerThreads | quote }}
            - name: ALERT_CONTROLLER_THREADS
              value: {{ .Values.alertControllerThreads | quote }}
            - name: KUBE_CLIENT_RATE_LIMIT_BURST
              value: {{ .Values.kubeClientRateLimitBurst | quote }}
            - name: KUBE_CLIENT_RATE_LIMIT_QPS
              value: {{ .Values.kubeClientRateLimitQPS | quote }}
            {{- if .Values.podSecurityStandard.enforce.level }}
            - name: RADIXOPERATOR_PODSECURITYSTANDARD_ENFORCE_LEVEL
              value: {{ .Values.podSecurityStandard.enforce.level }}
            {{- end }}
            {{- if .Values.podSecurityStandard.enforce.level }}
            - name: RADIXOPERATOR_PODSECURITYSTANDARD_APP_NAMESPACE_ENFORCE_LEVEL
              value: {{ .Values.podSecurityStandard.appNamespace.enforce.level }}
            {{- end }}
            {{- if .Values.podSecurityStandard.enforce.version }}
            - name: RADIXOPERATOR_PODSECURITYSTANDARD_ENFORCE_VERSION
              value: {{ .Values.podSecurityStandard.enforce.version }}
            {{- end }}
            {{- if .Values.podSecurityStandard.audit.level }}
            - name: RADIXOPERATOR_PODSECURITYSTANDARD_AUDIT_LEVEL
              value: {{ .Values.podSecurityStandard.audit.level }}
            {{- end }}
            {{- if .Values.podSecurityStandard.audit.version }}
            - name: RADIXOPERATOR_PODSECURITYSTANDARD_AUDIT_VERSION
              value: {{ .Values.podSecurityStandard.audit.version }}
            {{- end }}
            {{- if .Values.podSecurityStandard.warn.level }}
            - name: RADIXOPERATOR_PODSECURITYSTANDARD_WARN_LEVEL
              value: {{ .Values.podSecurityStandard.warn.level }}
            {{- end }}
            {{- if .Values.podSecurityStandard.warn.version }}
            - name: RADIXOPERATOR_PODSECURITYSTANDARD_WARN_VERSION
              value: {{ .Values.podSecurityStandard.warn.version }}
            {{- end }}
            - name: SECCOMP_PROFILE_FILENAME
              value: {{ .Values.seccompProfile.fileNameOnNode }}
            - name: RADIX_BUILDAH_IMAGE_BUILDER # TODO: Deprecated, remove
              value: {{ .Values.buildahImageBuilder }}
            - name: RADIX_BUILDKIT_IMAGE_BUILDER
              value: {{ .Values.buildKitImageBuilder }}
            - name: RADIX_PIPELINE_GIT_CLONE_NSLOOKUP_IMAGE
              value: {{ .Values.gitCloneNsLookupImage }}
            - name: RADIX_PIPELINE_GIT_CLONE_GIT_IMAGE
              value: {{ .Values.gitCloneGitImage }}
            - name: RADIX_PIPELINE_GIT_CLONE_BASH_IMAGE
              value: {{ .Values.gitCloneBashImage }}
            - name: RADIX_RESERVED_APP_DNS_ALIASES
              value: {{ include "helm-toolkit.utils.joinMapWithComma" .Values.reservedAppDNSAlias | quote }}
            - name: RADIX_RESERVED_DNS_ALIASES
              value: {{ include "helm-toolkit.utils.joinListWithComma" .Values.reservedDNSAlias | quote }}
            - name: RADIXOPERATOR_CERTIFICATE_AUTOMATION_CLUSTER_ISSUER
              value: {{ .Values.ingress.certificate.automation.clusterIssuer }}
            - name: RADIXOPERATOR_CERTIFICATE_AUTOMATION_DURATION
              value: {{ .Values.ingress.certificate.automation.duration }}
            - name: RADIXOPERATOR_CERTIFICATE_AUTOMATION_RENEW_BEFORE
              value: {{ .Values.ingress.certificate.automation.renewBefore }}  
            - name: RADIX_EXTERNAL_REGISTRY_DEFAULT_AUTH_SECRET
              value: {{ .Values.externalRegistryDefaultAuthSecret }}            
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 12 }}
          {{- end }}          
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}        
