apiVersion: v1
kind: Secret
metadata:
  name: radix-sp-acr-azure
  labels:
    app: "radix-operator"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  sp_credentials.json: {{ template "radix-sp-acr-azure-secret" . }}
