{{- if .Values.ingress.configuration}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: radix-operator-ingress-configmap
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
data:
  ingressConfiguration: |
{{ toYaml .Values.ingress | indent 4 }}
{{- end }}
