apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: radixdeployments.radix.equinor.com
spec:
  group: radix.equinor.com
  version: v1
  names:
    kind: RadixDeployment
    plural: radixdeployments
    singular: radixdeployment
    shortNames:
      - rd
  scope: Namespaced
