# defines roles for radix-job-scheduler-server
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-job-scheduler-server
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - pods/log
      - persistentvolumeclaims
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - radix.equinor.com
    resources:
      - radixdeployments
    verbs:
      - list
      - get
  - apiGroups:
      - radix.equinor.com
    resources:
      - radixbatches
    verbs:
      - list
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - '*'
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - '*'
    resources:
      - services
    verbs:
      - get
      - create
      - delete
      - list
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
  - apiGroups:
      - '*'
    resources:
      - events
    verbs:
      - get
      - list
  - apiGroups:
      - secrets-store.csi.x-k8s.io
    resources:
      - secretproviderclasses
    verbs:
      - get
      - list
---
