{{ if .Values.radixWebhook.enabled }}

{{- $secret := default (dict "data" (dict)) (lookup "v1" "Secret" .Release.Namespace .Values.radixWebhook.tlsSecretName) }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.radixWebhook.tlsSecretName | quote }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radix-webhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data: {{$secret.data}}

{{end}}