apiVersion: apps/v1
kind: Deployment
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radix-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radix-webhook
    spec:
      serviceAccountName: radix-webhook
      volumes:
        - name: radix-webhook-certs
          secret:
            secretName: radix-webhook-certs
      containers:
        - name: radix-webhook
          image: localhost/webhook:1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: radix-webhook-certs
              mountPath: /certs
              readOnly: true
          
          env:
            - name: PORT
              value: "8443"
            - name: CERT_DIR
              value: "/certs"
            - name: SECRET_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SECRET_NAME
              value: "radix-webhook-certs"
            - name: WEBHOOK_NAME
              value: radix-webhook-configuration

---
apiVersion: v1
kind: Service
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook
spec:
  ports:
    - port: 8443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: radix-webhook