apiVersion: v1
kind: ServiceAccount
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook
rules:
  - apiGroups: ["radix.equinor.com"]
    resources: ["radixregistrations"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["radix-webhook-certs"]
    verbs: ["get", "create", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "watch"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["get", "list", "watch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radix-webhook
subjects:
  - kind: ServiceAccount
    name: radix-webhook
    namespace: default #TODO: {{ .Release.Namespace }}