---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - radix.equinor.com
  resources:
  - radixregistrations
  - radixregistrations/status
  - radixapplications
  - radixenvironments
  - radixenvironments/status
  - radixdeployments
  - radixdeployments/status
  - radixjobs
  - radixjobs/status
  - radixalerts
  - radixalerts/status
  - radixscheduledjobs
  - radixscheduledjobs/status
  verbs:
  - get
  - list
  - watch
  - patch # required since radix operator grants this to others
  - delete # required since radix operator grants this to others
  - create # required since radix operator grants this to others
  - update # required since radix operator grants this to others
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch 
  - create
  - delete
  - update # required since radix operator grants this to others
  - patch
- apiGroups:
  - '*'
  resources:
  - events
  - limitranges
  - namespaces
  - secrets
  - serviceaccounts
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  - deployments
  - services
  - ingresses
  - servicemonitors
  - networkpolicies
  - storageclasses
  - persistentvolumeclaims
  - persistentvolumes
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list # required since radix operator grants this to others
  - watch # required since radix operator grants this to others
  - create # required since radix operator grants this to others
  - delete # required since radix operator grants this to others
  - patch # required since radix operator grants this to others
- apiGroups: # required since radix operator grants this to others
  - '*'
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - 'monitoring.coreos.com'
  resources:
  - alertmanagerconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - 'secrets-store.csi.x-k8s.io'
  resources:
  - secretproviderclasses
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - 'secrets-store.csi.x-k8s.io'
  resources:
  - secretproviderclasspodstatuses
  verbs:
  - get
  - list
- apiGroups:
    - tekton.dev
  resources:
    - pipelines
    - tasks
  verbs:
    - create
    - get
    - list
    - update
- apiGroups:
    - tekton.dev
  resources:
    - pipelineruns
  verbs:
    - create
    - get
    - list
    - watch
    - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
  name: {{ template "radix-operator.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ template "radix-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
