# defines roles for radix-job-scheduler-server
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-job-scheduler-server
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups:
      - '*'
    resources:
      - pods
      - pods/log
      - persistentvolumeclaims
    verbs:
      - get
      - list
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - radix.equinor.com
    resources:
      - radixdeployments
    verbs:
      - list
      - get
  - apiGroups:
      - '*'
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - '*'
    resources:
      - services
    verbs:
      - get
      - create
      - delete
      - list
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
      - create
      - update
  - apiGroups:
      - '*'
    resources:
      - events
    verbs:
      - get
      - list
---
