apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "radix-operator.selectorLabels" . | nindent 4 }}
  name: {{ template "radix-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  endpoints:
  - honorLabels: true
    port: metrics
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      {{- include "radix-operator.selectorLabels" . | nindent 6 }}
---
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations}}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "radix-operator.selectorLabels" . | nindent 4 }}
  name: {{ template "radix-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - name: metrics
    port: 9000
    protocol: TCP
    targetPort: metrics
  selector:
    matchLabels:
      {{- include "radix-operator.selectorLabels" . | nindent 6 }}
  type: ClusterIP
