apiVersion: v1
kind: Service
metadata:
  name: radix-api-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radix-api-server.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ include "radix-api-server.port" . }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ include "radix-api-server.metricsPort" . }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if .Values.config.apiServer.useProfiler }}
    - port: {{ include "radix-api-server.profilerPort" . }}
      targetPort: profiler
      protocol: TCP
      name: profiler
    {{- end }}
  selector:
    {{- include "radix-api-server.selectorLabels" . | nindent 4 }}
