---
# used to grant tekton access to create jobs in its app namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-tekton-runner
  labels:
    app: "radix-operator"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - radix.equinor.com
    resources:
      - radixapplications
      - radixregistrations
    verbs:
      - get
      - list
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
      - tasks
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
      - get
      - list
      - watch
      - update

