apiVersion: v1
kind: ConfigMap
metadata:
  name: radix-common-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
data:
  configYaml: |
    {{- .Values.config | toYaml | nindent 4 }}
