---
# used to grant tekton access to create jobs in its app namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-tekton
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
  - apiGroups:
      - tekton.dev
    resources:
      - pipelines
      - tasks
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
      - get
      - list
      - watch
      - update

