{{ if .Values.radixWebhook.enabled }}

kind: Secret
apiVersion: v1
metadata:
  name: radix-webhook-certs
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radix-webhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque

{{end}}