# defines roles for job-scheduler
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: radix-job-scheduler
  namespace: "{{ .Namespace }}"
  labels:
    app: "radix-job-scheduler"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: radix-job-scheduler-role-binding
  namespace: "{{ .Namespace }}"
  labels:
    app: "radix-job-scheduler"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: radix-job-scheduler
subjects:
  - kind: ServiceAccount
    name: radix-job-scheduler