apiVersion: v1
kind: ServiceAccount
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook
rules:
  - apiGroups: ["radix.equinor.com"]
    resources: ["radixregistrations"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["radix-webhook-certs"]
    verbs: ["get", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radix-webhook
subjects:
  - kind: ServiceAccount
    name: radix-webhook
    namespace: {{ .Release.Namespace }}