apiVersion: apps/v1
kind: Deployment
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radix-webhook
  template:
    metadata:
      labels:
        app.kubernetes.io/name: radix-webhook
    spec:
      serviceAccountName: radix-webhook
      volumes:
        - name: radix-webhook-certs
          secret:
            secretName: radix-webhook-certs
      containers:
        - name: radix-webhook
          image: localhost/webhook:13
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9443
              name: webhook
            - containerPort: 9440
              name: healthz
            - containerPort: 9000
              name: metrics
          readinessProbe:
            httpGet:
              path: /readyz
              port: healthz
          livenessProbe:
            httpGet: 
              path: /healthz
              port: healthz
          env:
            - name: LOG_LEVEL
              value: "trace"
            - name: LOG_PRETTY
              value: "true"
            - name: SECRET_NAMESPACE
              value: default
            - name: SECRET_NAME
              value: "radix-webhook-certs"
            - name: WEBHOOK_CONFIGURATION_NAME
              value: radix-webhook-configuration
            - name: CERTS_DIR
              value: /certs
            - name: REQUIRE_AD_GROUPS
              value: "true"
            - name: REQUIRE_CONFIGURATION_ITEM
              value: "true"
          volumeMounts:
            - name: radix-webhook-certs
              mountPath: /certs
              readOnly: true

---
apiVersion: v1
kind: Service
metadata:
  name: radix-webhook
  labels:
    app.kubernetes.io/name: radix-webhook
spec:
  ports:
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: radix-webhook