apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-app-reader
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - radix.equinor.com
    resources:
      - radixapplications
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - radix.equinor.com
    resources:
      - radixalerts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - radix.equinor.com
    resources:
      - radixjobs
    verbs:
      - get
      - list
  - apiGroups:
      - '*'
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - get
      - list
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
    verbs:
      - get
      - list
