---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: radix-api-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radix-api-server.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "radix-api-server.labels" . | nindent 4 }}
  name: radix-api
rules:
rules:
- apiGroups:
  - radix.equinor.com
  resources:
  - radixregistrations
  - radixapplications
  - radixdeployments
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - radix.equinor.com
  resources:
  - radixenvironments
  verbs:
  - get
  - list
  - watch
  - delete
  - create
- apiGroups:
  - '*'
  resources:
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - '*'
  resources:
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - radix.equinor.com
  resources:
  - radixjobs
  verbs:
  - get
  - list
  - watch
  - patch
  - create
- apiGroups:
  - 'secrets-store.csi.x-k8s.io'
  resources:
  - secretproviderclasses
  - secretproviderclasspodstatuses
  verbs:
  - get
  - list
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - 'cert-manager.io'
  resources:
  - certificates
  - certificaterequests
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
  name: radix-access-validation
rules:
- apiGroups:
  - '*'
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - delete
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "radix-api-server.labels" . | nindent 4 }}
  name: radix-api-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radix-api
subjects:
- kind: ServiceAccount
  name: radix-api-server
  namespace: {{ .Release.Namespace }}
---
# Add rolebind for radix-access-validation to allow radix-api to validate access for users
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "radix-api-server.labels" . | nindent 4 }}
  name: radix-api-access-validation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radix-access-validation
subjects:
- kind: ServiceAccount
  name: radix-api-server
  namespace: {{ .Release.Namespace }}
