---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: radix-operator
  labels:
    app: "radix-operator"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: "radix-operator"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: radix-operator
rules:
- apiGroups:
  - '*'
  resources:
  - configmaps #remove 
  - namespaces
  - secrets
  - serviceaccount
  - role
  - rolebinding
  - clusterrole
  - clusterrolebinding
  - deployment
  - service
  - ingress
  - servicemonitor
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: radix-operator
  labels:
    app: "radix-operator"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  namespace: default
  name: radix-operator
roleRef:
  kind: ClusterRole
  name: radix-operator
  apiGroup: rbac.authorization.k8s.io