apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: radixdeployments.radix.equinor.com
  labels:
    app: "radix-operator"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  group: radix.equinor.com
  names:
    kind: RadixDeployment
    plural: radixdeployments
    singular: radixdeployment
    shortNames:
      - rd
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
