apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-app-reader-envs
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - radix.equinor.com
  resources:
  - radixdeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - radix.equinor.com
  resources:
  - radixalerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - radix.equinor.com
  resources:
  - radixbatches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - get
  - list
- apiGroups:
  - '*'
  resources:
  - pods
  - pods/log
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - get
  - list
  - watch
