apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: radix-operator
  name: radix-operator
  namespace: default
spec:
  endpoints:
  - honorLabels: true
    port: metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: radix-operator
---
apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations}}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: radix-operator
    operater-radix: "true"
  name: radix-operator
  namespace: default
spec:
  ports:
  - name: metrics
    port: 9000
    protocol: TCP
    targetPort: metrics
  selector:
    app: radix-operator
  type: ClusterIP
