apiVersion: apps/v1
kind: Deployment
metadata:
  name: radix-api-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radix-api-server.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "radix-api-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "radix-api-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: radix-api-server

      {{- with .Values.radixApiServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.radixApiServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.radixApiServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.radixApiServer.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.radixApiServer.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.radixApiServer.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}

      containers:
        - name: radix-api-server
          image: {{ .Values.radixApiServer.image.repository }}:{{ .Values.radixApiServer.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent

          {{- with .Values.radixApiServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.radixApiServer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          ports:
            - containerPort: {{ .Values.config.apiServer.port }}
              name: http
            - containerPort: {{ .Values.config.apiServer.metricsPort }}
              name: metrics
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RADIX_COMMON_CONFIG_NAME
              value: {{ include "radix-common-config.name" . }}
            - name: RADIX_COMMON_CONFIG_KEY
              value: "configYaml"