apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "radix-common-config.name" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
data:
  configYaml: |
    {{- .Values.config | toYaml | nindent 4 }}
