{{ if .Values.radixWebhook.enabled }}
{{- $secretName := include "radix-webhook.secret.fullname" . }}
{{- $secret := default (dict "data") (lookup "v1" "Secret" .Release.Namespace $secretName) }}

kind: Secret
apiVersion: v1
metadata:
  name: {{ template "radix-webhook.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "radix-webhook.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": "pre-install"
type: Opaque
data: {{ default "{}" $secret.data }}

{{end}}