apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: radixapplications.radix.equinor.com
  labels:
    {{- include "radix-operator.labels" . | nindent 4 }}
spec:
  group: radix.equinor.com
  names:
    kind: RadixApplication
    plural: radixapplications
    singular: radixapplication
    shortNames:
      - ra
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
