---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    app: {{ template "radix-operator.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ if .Values.rbac.enabled }}
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: radix-deploy
#   labels:
#     app: {{ template "radix-operator.name" . }}
#     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
#     release: "{{ .Release.Name }}"
#     heritage: "{{ .Release.Service }}"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    app: {{ template "radix-operator.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ["radix.equinor.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets", "configmaps", "pods", "namespaces", "rolebindings", "deployments"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    app: {{ template "radix-operator.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  namespace: default
  name: {{ template "radix-operator.fullname" . }}
roleRef:
  kind: ClusterRole
#  name: {{ template "radix-operator.fullname"  .}}
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
{{ end }}
