---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    app: {{ template "radix-operator.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{ if .Values.rbac.enabled }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    app: {{ template "radix-operator.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ["radix.equinor.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets", "configmaps", "pods", "namespaces"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "radix-operator.fullname" . }}
  labels:
    app: {{ template "radix-operator.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
subjects:
- kind: ServiceAccount
  name: {{ template "radix-operator.fullname" . }}
roleRef:
  kind: Role
  name: {{ template "radix-operator.fullname"  .}}
  apiGroup: rbac.authorization.k8s.io
{{ end }}
