apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.seccompProfile.installer.daemonSetName }}
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: {{ .Values.seccompProfile.installer.daemonSetName }}
  template:
    metadata:
      labels:
        app: {{ .Values.seccompProfile.installer.daemonSetName }}
    spec:
      imagePullSecrets:
        {{- range .Values.seccompProfile.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "nodepool-type"
                operator: NotIn
                values: ["system"]
      containers:
        - name: file-copy-container
          image: {{ .Values.seccompProfile.image.repository }}:{{ .Values.seccompProfile.image.tag }}
          command: ["sh", "-c"]
          args: ["while true; do if ! diff -q /configmap-data/{{ .Values.seccompProfile.fileNameOnNode }} /hostpath/{{ .Values.seccompProfile.fileNameOnNode }} > /dev/null 2>&1; then echo \"$(date ''+%H:%M'') - Changes\" && cp /configmap-data/{{ .Values.seccompProfile.fileNameOnNode }} /hostpath/; else echo \"$(date ''+%H:%M'') - No changes\"; fi; sleep 60; done"]
          volumeMounts:
            - name: hostpath-volume
              mountPath: /hostpath
            - name: configmap-volume
              mountPath: /configmap-data
              readOnly: true
          {{- if .Values.seccompProfile.installer.resources }}
          resources:
            {{- toYaml .Values.seccompProfile.installer.resources | nindent 12 }}
          {{- end}}
      volumes:
        - name: hostpath-volume
          hostPath:
            path: /var/lib/kubelet/seccomp
        - name: configmap-volume
          configMap:
            name: {{ .Values.seccompProfile.installer.configMapName }}
      tolerations:
        - operator: Exists
