// Code generated by MockGen. DO NOT EDIT.
// Source: ./pipeline-runner/utils/git/git.go
//
// Generated by this command:
//
//	mockgen -source ./pipeline-runner/utils/git/git.go -destination ./pipeline-runner/utils/git/git_mock.go -package git
//

// Package git is a generated GoMock package.
package git

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Checkout mocks base method.
func (m *MockRepository) Checkout(reference string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", reference)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkout indicates an expected call of Checkout.
func (mr *MockRepositoryMockRecorder) Checkout(reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockRepository)(nil).Checkout), reference)
}

// CommitExists mocks base method.
func (m *MockRepository) CommitExists(commitHash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitExists", commitHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommitExists indicates an expected call of CommitExists.
func (mr *MockRepositoryMockRecorder) CommitExists(commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitExists", reflect.TypeOf((*MockRepository)(nil).CommitExists), commitHash)
}

// DiffCommits mocks base method.
func (m *MockRepository) DiffCommits(beforeCommitHash, targetCommitHash string) (DiffEntries, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiffCommits", beforeCommitHash, targetCommitHash)
	ret0, _ := ret[0].(DiffEntries)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiffCommits indicates an expected call of DiffCommits.
func (mr *MockRepositoryMockRecorder) DiffCommits(beforeCommitHash, targetCommitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiffCommits", reflect.TypeOf((*MockRepository)(nil).DiffCommits), beforeCommitHash, targetCommitHash)
}

// IsAncestor mocks base method.
func (m *MockRepository) IsAncestor(ancestor, other string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAncestor", ancestor, other)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAncestor indicates an expected call of IsAncestor.
func (mr *MockRepositoryMockRecorder) IsAncestor(ancestor, other any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAncestor", reflect.TypeOf((*MockRepository)(nil).IsAncestor), ancestor, other)
}

// ResolveCommitForReference mocks base method.
func (m *MockRepository) ResolveCommitForReference(reference string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCommitForReference", reference)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCommitForReference indicates an expected call of ResolveCommitForReference.
func (mr *MockRepositoryMockRecorder) ResolveCommitForReference(reference any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCommitForReference", reflect.TypeOf((*MockRepository)(nil).ResolveCommitForReference), reference)
}

// ResolveTagsForCommit mocks base method.
func (m *MockRepository) ResolveTagsForCommit(commitHash string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveTagsForCommit", commitHash)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveTagsForCommit indicates an expected call of ResolveTagsForCommit.
func (mr *MockRepositoryMockRecorder) ResolveTagsForCommit(commitHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveTagsForCommit", reflect.TypeOf((*MockRepository)(nil).ResolveTagsForCommit), commitHash)
}
