apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "testchart2.fullname" . }}-validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "testchart2.fullname" . }}-
  labels:
  {{- include "testchart2.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: '{{ .Release.Namespace }}'
      path: /radix/v1/radixregistration/validater
  failurePolicy: Fail
  name: validate.radixapplication.radix.equinor.com
  rules:
  - apiGroups:
    - radix.equinor.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - radixregistrations
  sideEffects: None
