apiVersion: v1
kind: ServiceAccount
metadata:
  name: radix-webhook
  labels:
  {{- include "testchart2.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.radixWebhook.serviceAccount.annotations | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radix-webhook
  labels:
  {{- include "testchart2.labels" . | nindent 4 }}
rules:
- apiGroups:
  - radix.equinor.com
  resources:
  - radixregistrations
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resourceNames:
  - radix-webhook-certs
  resources:
  - secrets
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: radix-webhook
  labels:
  {{- include "testchart2.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radix-webhook
subjects:
- kind: ServiceAccount
  name: radix-webhook
  namespace: '{{ .Release.Namespace }}'
