apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "testchart2.fullname" . }}-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "testchart2.fullname" . }}-
  labels:
  {{- include "testchart2.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: radix-webhook
      namespace: '{{ .Release.Namespace }}'
      path: /api/v1/radixregistration/validator
      port: 8443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: radixregistrations.validation.radix.equinor.com
  rules:
  - apiGroups:
    - radix.equinor.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - radixregistrations
  sideEffects: None
