// Code generated by MockGen. DO NOT EDIT.
// Source: ./radix-operator/dnsalias/internal/syncerfactory.go

// Package internal is a generated GoMock package.
package internal

import (
	reflect "reflect"

	dnsalias "github.com/equinor/radix-operator/pkg/apis/dnsalias"
	kube "github.com/equinor/radix-operator/pkg/apis/kube"
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	versioned "github.com/equinor/radix-operator/pkg/client/clientset/versioned"
	gomock "github.com/golang/mock/gomock"
	kubernetes "k8s.io/client-go/kubernetes"
)

// MockSyncerFactory is a mock of SyncerFactory interface.
type MockSyncerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSyncerFactoryMockRecorder
}

// MockSyncerFactoryMockRecorder is the mock recorder for MockSyncerFactory.
type MockSyncerFactoryMockRecorder struct {
	mock *MockSyncerFactory
}

// NewMockSyncerFactory creates a new mock instance.
func NewMockSyncerFactory(ctrl *gomock.Controller) *MockSyncerFactory {
	mock := &MockSyncerFactory{ctrl: ctrl}
	mock.recorder = &MockSyncerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncerFactory) EXPECT() *MockSyncerFactoryMockRecorder {
	return m.recorder
}

// CreateSyncer mocks base method.
func (m *MockSyncerFactory) CreateSyncer(kubeClient kubernetes.Interface, kubeUtil *kube.Kube, radixClient versioned.Interface, radixDNSAlias *v1.RadixDNSAlias) dnsalias.Syncer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncer", kubeClient, kubeUtil, radixClient, radixDNSAlias)
	ret0, _ := ret[0].(dnsalias.Syncer)
	return ret0
}

// CreateSyncer indicates an expected call of CreateSyncer.
func (mr *MockSyncerFactoryMockRecorder) CreateSyncer(kubeClient, kubeUtil, radixClient, radixDNSAlias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncer", reflect.TypeOf((*MockSyncerFactory)(nil).CreateSyncer), kubeClient, kubeUtil, radixClient, radixDNSAlias)
}
