// Code generated by MockGen. DO NOT EDIT.
// Source: ./job-scheduler/pkg/notifications/notifier.go

// Package notifications is a generated GoMock package.
package notifications

import (
	reflect "reflect"

	events "github.com/equinor/radix-operator/job-scheduler/models/v1/events"
	v1 "github.com/equinor/radix-operator/pkg/apis/radix/v1"
	gomock "go.uber.org/mock/gomock"
)

// MockNotifier is a mock of Notifier interface.
type MockNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockNotifierMockRecorder
}

// MockNotifierMockRecorder is the mock recorder for MockNotifier.
type MockNotifierMockRecorder struct {
	mock *MockNotifier
}

// NewMockNotifier creates a new mock instance.
func NewMockNotifier(ctrl *gomock.Controller) *MockNotifier {
	mock := &MockNotifier{ctrl: ctrl}
	mock.recorder = &MockNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotifier) EXPECT() *MockNotifierMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockNotifier) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockNotifierMockRecorder) Enabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockNotifier)(nil).Enabled))
}

// Notify mocks base method.
func (m *MockNotifier) Notify(event events.Event, radixBatch *v1.RadixBatch, jobStatuses []v1.RadixBatchJobStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", event, radixBatch, jobStatuses)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockNotifierMockRecorder) Notify(event, radixBatch, jobStatuses interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotifier)(nil).Notify), event, radixBatch, jobStatuses)
}

// String mocks base method.
func (m *MockNotifier) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockNotifierMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockNotifier)(nil).String))
}
