// Code generated by MockGen. DO NOT EDIT.
// Source: ./api-server/api/environments/environment_handler.go
//
// Generated by this command:
//
//	mockgen -source ./api-server/api/environments/environment_handler.go -destination ./api/environments/mock/environment_handler_mock.go -package mock
//

// Package mock is a generated GoMock package.
package mock
