# Default values for radix-operator.

clusterName: clusterz

appAliasBaseURL: app.dev.radix.equinor.com
dnsZone: dev.radix.equinor.com

imagePullSecretName: radix-docker
imageRegistry: radixdev.azurecr.io

app:
  # Limit range on app namespace
  limitrange:
    default:
      memory: 1G
      cpu: 1
    defaultReqest:
      memory: 500M
      cpu: 0.25
  env:
    # Limit range on env namespace
    limitrange:
      default:
        memory: 1G
        cpu: 1
      defaultReqest:
        memory: 500M
        cpu: 0.25

rbac:
  enabled: true

replicaCount: 1

image:
  repository: radix-operator
  tag: "release-latest"
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 9000

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

prometheusName: kube-prometheus