# Default values for radix-operator.

clusterName: clusterz
infrastructureEnvironment: envivonmentz

appAliasBaseURL: app.dev.radix.equinor.com

imagePullSecretName: radix-docker
imageRegistry: radixdev.azurecr.io

rbac:
  enabled: true

replicaCount: 1

image:
  repository: radix-operator
  tag: "release-latest"
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 9000

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

prometheusName: kube-prometheus