# Default values for radix-operator.
nameOverride: ""
fullnameOverride: ""
clusterName: xx
activeClusterName: xx
clusterActiveEgressIps: xx

registrationControllerThreads: 1
applicationControllerThreads: 1
environmentControllerThreads: 1
deploymentControllerThreads: 1
jobControllerThreads: 1
alertControllerThreads: 1
kubeClientRateLimitBurst: 5
kubeClientRateLimitQPS: 5

configToMap: radix-config-2-map:master-latest
imageBuilder: radix-image-builder:master-latest
buildKitImageBuilder: radix-buildkit-builder:main-latest # TODO: Configure in radix-flux
buildahImageBuilder: xx # TODO: Deprecated, remove
jobScheduler: radix-job-scheduler:main-latest
radixTekton: radix-tekton:main-latest

# Images used by git clone init containers in pipeline
gitCloneNsLookupImage: "" # Image containing nslookup, e.g. "alpine:3.20". Defaults to "alpine:latest" if not set
gitCloneGitImage: "" # Image containing git, e.g. "alpine/git:2.45.2". Defaults to "alpine/git:latest" if not set
gitCloneBashImage: "" # Image containing bash, e.g. "bash:5.2". Defaults to "bash:latest" if not set

reservedAppDNSAlias:
  api: radix-api
  canary: radix-canary-golang
  console: radix-web-console
  cost-api: radix-cost-allocation-api
  webhook: radix-github-webhook
reservedDNSAlias:
  - grafana
  - prometheus
  - www
  - app
  - playground
  - dev

appAliasBaseURL: app.dev.radix.equinor.com
dnsZone: dev.radix.equinor.com
radixZone: xx
containerRegistry: radixdev.azurecr.io
appContainerRegistry: radixdevapp.azurecr.io
tenantId: xx
subscriptionId: xx

app:
  # Limit range on app namespace
  limitrange:
    default:
      memory: 450M
    defaultRequest:
      memory: 450M
      cpu: 100m
  env:
    # Limit range on env namespace
    limitrange:
      default:
        memory: 500M
      defaultRequest:
        memory: 500M
        cpu: 100m
  builder:
    # Limit range on builder job in app namespace
    resources:
      limits:
        memory: 500M
      requests:
        memory: 500M
        cpu: 200m
  # Readiness probe parameters
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  # Rolling update parameters
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

replicaCount: 1

image:
  repository: xx
  tag: xx
  pullPolicy: Always

service:
  # annotations: {}
  type: ClusterIP
  internalPort: 9000

serviceAccount:
  # The name of the service account to use.
  # If not set, a name is generated using the fullname template
  name: ""

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

ingress:
  certificate:
    automation:
      clusterIssuer: ""
      duration: "2160h"
      renewBefore: "720h"
  configuration:
    - name: websocketfriendly
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
        nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
    - name: stickysessions
      annotations:
        nginx.ingress.kubernetes.io/affinity: cookie
        nginx.ingress.kubernetes.io/session-cookie-hash: sha1
        nginx.ingress.kubernetes.io/session-cookie-name: INGRESSCOOKIE
    - name: leastconnectedlb
      annotations:
        nginx.org/lb-method: random

nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  supplementalGroups:
    - 1000

securityContext:
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

# Additional volumes to add to the radix-cost-allocation pod.
volumes: []

# Additional volume mounts to add to the radix-cost-allocation container.
volumeMounts: []

prometheusName: kube-prometheus

clusterType: development

radixGroups:
  clusterAdmin: "a5dfa635-dc00-4a28-9ad9-9e7f1e56919d"
  user: "64b28659-4fe4-4222-8497-85dd7e43e25b"
  playground: "4b8ec60e-714c-4a9d-8e0a-3e4cfb3c3d31"

deploymentsPerEnvironmentHistoryLimit: 10
pipelineJobsHistoryLimit: 5
pipelineJobsHistoryPeriodLimit: "720h"
logLevel: "INFO"
logPretty: false
oauthProxyDefaultIssuerUrl: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
oauthProxyImage: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0
externalRegistryDefaultAuthSecret: "" # Name of the secret containing default container registry credentials for pulling images when building with buildah and pulling external images for components and jobs

seccompProfile:
  fileNameOnNode: allow-buildah.json
  installer:
    image: docker.io/alpine:3.20
    configMapName: "seccomp-allow-buildah"
    daemonSetName: copy-seccomp-profile
    resources:
      limits:
        cpu: 10m
        memory: 10Mi
      requests:
        cpu: 10m
        memory: 10Mi

# Ref https://kubernetes.io/docs/concepts/security/pod-security-standards/ for docs and valid values for level and version
podSecurityStandard:
  appNamespace:
    enforce:
      level: privileged
      version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
  enforce:
    level: "" # One of privileged, baseline, restricted
    version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
  audit:
    level: "" # One of privileged, baseline, restricted
    version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
  warn:
    level: "" # One of privileged, baseline, restricted
    version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
