# Default values for radix-operator.

rbac:
  enabled: true

replicaCount: 1

image:
  repository: radix-operator
  tag: "latest"
  pullPolicy: Always

imageCredentials:
  registry: radixdev.azurecr.io
  username: someone
  password: sillyness

service:
  type: ClusterIP
  internalPort: 9000

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

clustername: clusterz

# This is a workaround until https://github.com/Azure/AKS/issues/676 gets fixed
clusterFQDN: mycluster-xx-xx.hcp.northeurope.azmk8s.io