# Default values for radix-operator.
nameOverride: ""
fullnameOverride: ""
clusterName: xx
activeClusterName: xx
clusterActiveEgressIps: xx

imageBuilder: radix-image-builder:master-latest
imageScanner: radix-image-scanner:master-latest
jobScheduler: radix-job-scheduler-server:main-latest
radixTekton: radix-tekton:main-latest

appAliasBaseURL: app.dev.radix.equinor.com
dnsZone: dev.radix.equinor.com
containerRegistry: radixdev.azurecr.io
tenantId: xx
subscriptionId: xx

app:
  # Limit range on app namespace
  limitrange:
    default:
      memory: 450M
      cpu: 2000m
    defaultRequest:
      memory: 450M
      cpu: 5m
  env:
    # Limit range on env namespace
    limitrange:
      default:
        memory: 500M
        cpu: 2000m
      defaultRequest:
        memory: 500M
        cpu: 50m
  # Readiness probe parameters
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  # Rolling update parameters
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

replicaCount: 1

image:
  repository: xx
  tag: xx
  pullPolicy: Always

service:
  # annotations: {}
  type: ClusterIP
  internalPort: 9000

serviceAccount:
  # The name of the service account to use.
  # If not set, a name is generated using the fullname template
  name: ""

resources: 
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

ingress:
  configuration:
    - name: websocketfriendly
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
        nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
    - name: stickysessions
      annotations:
        nginx.ingress.kubernetes.io/affinity: cookie
        nginx.ingress.kubernetes.io/session-cookie-hash: sha1
        nginx.ingress.kubernetes.io/session-cookie-name: INGRESSCOOKIE
    - name: leastconnectedlb
      annotations:
        nginx.org/lb-method: random

nodeSelector: {}

tolerations: []

affinity: {}

prometheusName: kube-prometheus

clusterType: development

radixGroups:
  clusterAdmin: "a5dfa635-dc00-4a28-9ad9-9e7f1e56919d"
  user: "64b28659-4fe4-4222-8497-85dd7e43e25b"
  playground: "4b8ec60e-714c-4a9d-8e0a-3e4cfb3c3d31"

deploymentsPerEnvironmentHistoryLimit: 10
jobsPerAppHistoryLimit: 20
logLevel: "INFO"
forceNonRootDeploymentContainers: false
oauthProxyDefaultIssuerUrl: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
oauthProxyImage: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0