# Default values for radix-operator.

clusterName: clusterz

appAliasBaseURL: app.dev.radix.equinor.com
dnsZone: dev.radix.equinor.com

imagePullSecretName: radix-docker

imageCredentials:
  registry: radixdev.azurecr.io
  username: xx
  password: xx

cicdacr:
  name: xx
  id: x
  password: xx
  tenantId: xx

rbac:
  enabled: true

replicaCount: 1

image:
  repository: radix-operator
  tag: "release-latest"
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 9000

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

prometheusName: kube-prometheus

# By setting this to true we will add the
# playground user group
isPlaygroundCluster: false

radixGroups:
  clusterAdmin: "a5dfa635-dc00-4a28-9ad9-9e7f1e56919d" # "fg_radix_platform_development"
  user: "64b28659-4fe4-4222-8497-85dd7e43e25b"
  playground: "4b8ec60e-714c-4a9d-8e0a-3e4cfb3c3d31"