# Default values for radix-operator.

clusterName: clusterz

appAliasBaseURL: app.dev.radix.equinor.com
dnsZone: dev.radix.equinor.com

imagePullSecretName: radix-docker

imageCredentials:
  registry: radixdev.azurecr.io
  username: xx
  password: xx

cicdacr:
  name: xx
  id: x
  password: xx
  tenantId: xx

rbac:
  enabled: true

replicaCount: 1

image:
  repository: radix-operator
  tag: "release-latest"
  pullPolicy: Always

service:
  type: ClusterIP
  internalPort: 9000

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

prometheusName: kube-prometheus

radixClusterAdminGroup: "604bad73-c53b-4a95-ab17-d7953f75c8c3" # "fg_radix_platform_development"
radixUserGroup: "7552642f-ad75-4e9d-a140-3ab8f3742c16"