# Default values for radix-operator.
nameOverride: ""
fullnameOverride: ""
clusterName: xx

registrationControllerThreads: 1
applicationControllerThreads: 1
environmentControllerThreads: 1
deploymentControllerThreads: 1
jobControllerThreads: 1
alertControllerThreads: 1
kubeClientRateLimitBurst: 5
kubeClientRateLimitQPS: 5

reservedAppDNSAlias:
  api: radix-api
  canary: radix-canary-golang
  console: radix-web-console
  cost-api: radix-cost-allocation-api
  webhook: radix-github-webhook
reservedDNSAlias:
  - grafana
  - prometheus
  - www
  - app
  - playground
  - dev

appAliasBaseURL: app.dev.radix.equinor.com
dnsZone: dev.radix.equinor.com
radixZone: xx
containerRegistry: radixdev.azurecr.io
appContainerRegistry: radixdevapp.azurecr.io
tenantId: xx
subscriptionId: xx

app:
  # Limit range on app namespace
  limitrange:
    default:
      memory: 450M
    defaultRequest:
      memory: 450M
      cpu: 100m
  env:
    # Limit range on env namespace
    limitrange:
      default:
        memory: 500M
      defaultRequest:
        memory: 500M
        cpu: 100m
  builder:
    # Limit range on builder job in app namespace
    resources:
      limits:
        memory: 500M
        cpu: 2000m
      requests:
        memory: 500M
        cpu: 200m
  # Readiness probe parameters
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  # Rolling update parameters
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

replicaCount: 1

image:
  repository: ghcr.io/equinor/radix/operator
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: Always
  pullSecrets: [] # List of image pull secret names to use for the radix-operator image

service:
  # annotations: {}
  type: ClusterIP
  internalPort: 9000

serviceAccount:
  # The name of the service account to use.
  # If not set, a name is generated using the fullname template
  name: ""

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

ingress:
  certificate:
    automation:
      clusterIssuer: ""
      duration: "2160h"
      renewBefore: "720h"
  configuration:
    - name: websocketfriendly
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
        nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
    - name: stickysessions
      annotations:
        nginx.ingress.kubernetes.io/affinity: cookie
        nginx.ingress.kubernetes.io/session-cookie-hash: sha1
        nginx.ingress.kubernetes.io/session-cookie-name: INGRESSCOOKIE
    - name: leastconnectedlb
      annotations:
        nginx.org/lb-method: random

task:
  orphanedEnvironmentsRetentionPeriod: 720h
  orphanedEnvironmentsCleanupCron: "0 0 * * *"
nodeSelector: {}

tolerations: []

affinity: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  supplementalGroups:
    - 1000

securityContext:
  privileged: false
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

# Additional volumes to add to the radix-cost-allocation pod.
volumes: []

# Additional volume mounts to add to the radix-cost-allocation container.
volumeMounts: []

clusterType: development

rbac:
  createApp:
    groups: [] # List of groups with permission to create new RadixRegistation

deploymentsPerEnvironmentHistoryLimit: 10
pipelineJobsHistoryLimit: 5
pipelineJobsHistoryPeriodLimit: "720h"
logLevel: "INFO"
logPretty: false
oauthProxyDefaultIssuerUrl: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
externalRegistryDefaultAuthSecret: "" # Name of the secret containing default container registry credentials for pulling images when building with buildah and pulling external images for components and jobs

seccompProfile:
  fileNameOnNode: allow-buildah.json
  image:
    tag: "3.20"
    repository: docker.io/alpine
    pullSecrets: [] # List of secret names to use
  installer:
    configMapName: "seccomp-allow-buildah"
    daemonSetName: copy-seccomp-profile
    resources:
      limits:
        cpu: 10m
        memory: 10Mi
      requests:
        cpu: 10m
        memory: 10Mi

# Ref https://kubernetes.io/docs/concepts/security/pod-security-standards/ for docs and valid values for level and version
podSecurityStandard:
  appNamespace:
    enforce:
      level: privileged
      version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
  enforce:
    level: "" # One of privileged, baseline, restricted
    version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
  audit:
    level: "" # One of privileged, baseline, restricted
    version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
  warn:
    level: "" # One of privileged, baseline, restricted
    version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"

# Image containing git
gitClone:
  image:
    repository: docker.io/alpine/git
    tag: "2.45.2"

oauth2proxy:
  image:
    repository: quay.io/oauth2-proxy/oauth2-proxy
    tag: "v7.9.0"

oauth2redis:
  image:
    repository: docker.io/redis
    tag: "8.0"

radixPipelineRunner:
  image:
    repository: ghcr.io/equinor/radix/pipeline
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

radixImageBuilder:
  image: 
    repository: ghcr.io/equinor/radix/image-builder
    tag: latest

radixBuildKitImageBuilder:
  image:
    repository: ghcr.io/equinor/radix/buildkit-builder
    tag: latest

radixJobScheduler:
  image:
    repository: ghcr.io/equinor/radix/job-scheduler
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

radixWebhook:
  enabled: false

  logLevel: info
  logPretty: false
  requireAdGroups: true
  requireConfigurationItem: true

  image: 
    repository: ghcr.io/equinor/radix/webhook
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
    pullPolicy: IfNotPresent
    pullSecrets: [] # List of image pull secret names to use for the webhook image

  resources:
    limits:
      memory: 1Gi
      cpu: 1000m
    requests:
      cpu: 100m
      memory: 100Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  # Extra pod labels
  podLabels: {}
  # Annotations to add to the pod

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000

  securityContext:
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
