# Default values for radix-operator.
nameOverride: ""
fullnameOverride: ""
clusterName: xx
activeClusterName: xx
clusterActiveEgressIps: xx

registrationControllerThreads: 1
applicationControllerThreads: 1
environmentControllerThreads: 1
deploymentControllerThreads: 1
jobControllerThreads: 1
alertControllerThreads: 1
kubeClientRateLimitBurst: 5
kubeClientRateLimitQPS: 5

configToMap: radix-config-2-map:master-latest
imageBuilder: radix-image-builder:master-latest
jobScheduler: radix-job-scheduler:main-latest
radixTekton: radix-tekton:main-latest
useImageBuilderCache: 0

appAliasBaseURL: app.dev.radix.equinor.com
dnsZone: dev.radix.equinor.com
radixZone: xx
containerRegistry: radixdev.azurecr.io
tenantId: xx
subscriptionId: xx

app:
  # Limit range on app namespace
  limitrange:
    default:
      memory: 450M
      cpu: 2000m
    defaultRequest:
      memory: 450M
      cpu: 100m
  env:
    # Limit range on env namespace
    limitrange:
      default:
        memory: 500M
        cpu: 2000m
      defaultRequest:
        memory: 500M
        cpu: 50m
  # Readiness probe parameters
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  # Rolling update parameters
  rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

replicaCount: 1

image:
  repository: xx
  tag: xx
  pullPolicy: Always

service:
  # annotations: {}
  type: ClusterIP
  internalPort: 9000

serviceAccount:
  # The name of the service account to use.
  # If not set, a name is generated using the fullname template
  name: ""

resources: 
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

ingress:
  configuration:
    - name: websocketfriendly
      annotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: 3600
        nginx.ingress.kubernetes.io/proxy-send-timeout: 3600
    - name: stickysessions
      annotations:
        nginx.ingress.kubernetes.io/affinity: cookie
        nginx.ingress.kubernetes.io/session-cookie-hash: sha1
        nginx.ingress.kubernetes.io/session-cookie-name: INGRESSCOOKIE
    - name: leastconnectedlb
      annotations:
        nginx.org/lb-method: random

nodeSelector: {}

tolerations: []

affinity: {}

prometheusName: kube-prometheus

clusterType: development

radixGroups:
  clusterAdmin: "a5dfa635-dc00-4a28-9ad9-9e7f1e56919d"
  user: "64b28659-4fe4-4222-8497-85dd7e43e25b"
  playground: "4b8ec60e-714c-4a9d-8e0a-3e4cfb3c3d31"

deploymentsPerEnvironmentHistoryLimit: 10
pipelineJobsHistoryLimit: 5
logLevel: "INFO"
oauthProxyDefaultIssuerUrl: https://login.microsoftonline.com/3aa4a235-b6e2-48d5-9195-7fcf05b459b0/v2.0
oauthProxyImage: quay.io/oauth2-proxy/oauth2-proxy:v7.2.0

# Ref https://kubernetes.io/docs/concepts/security/pod-security-standards/ for docs and valid values for level and version
podSecurityStandard:
  enforce:
    level: "" # One of privileged, baseline, restricted
    version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
  audit:
    level: "" # One of privileged, baseline, restricted
    version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
  warn:
    level: "" # One of privileged, baseline, restricted
    version: "" # "latest" or a kubernetes minor version, e.g. "v1.23" or "v1.24"
