# Default values for radix-operator.

rbac:
  enabled: true

replicaCount: 1

image:
  repository: radix-operator
  tag: "7be3d6f"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  internalPort: 9000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

privateRegistrySecret: radix-docker
privateRegistry: radixdev.azurecr.io