name: radix-operator-build

on:
  push:
    branches:
      - master
      - release
permissions:
  id-token: write
jobs:
  build-operator:
    name: Build-push-operator
    env:
      IMAGE: radix-operator
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: build operator
        run: |
          docker build . -f operator.Dockerfile -t radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} -t radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: 'Login to ACR radixdev'
        run: |
          az acr login --name radixdev
      - name: push to radixdev
        run: |
          docker push radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
      - name: push to radixprod
        run: |
          docker push radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
  build-pipeline:
    name: Build-push-pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build pipeline
        run: |
          docker build . -f pipeline.Dockerfile -t radixdev.azurecr.io/radix-pipeline:${GITHUB_REF##*/}-latest -t radixprod.azurecr.io/radix-pipeline:${GITHUB_REF##*/}-latest
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: 'Login to ACR radixdev'
        run: |
          az acr login --name radixdev
      - name: push to radixdev
        run: |
          docker push radixdev.azurecr.io/radix-pipeline:${GITHUB_REF##*/}-latest
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
      - name: 'Login to ACR radixprod'
        run: |
          az acr login --name radixprod
      - name: push to radixprod
        run: |
          docker push radixprod.azurecr.io/radix-pipeline:${GITHUB_REF##*/}-latest