name: radix-operator-build
on:
  push:
    branches:
      - master
      - release
jobs:
  build-operator:
    name: Build-push-operator
    env:
      IMAGE: radix-cicd-canary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: build operator
        run: |
          docker build . -f operator.Dockerfile -t radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} -t radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
      - uses: azure/docker-login@v1
        with:
          login-server: radixdev.azurecr.io
          username: ${{ secrets.DEV_REGISTRY_USERNAME }}
          password: ${{ secrets.DEV_REGISTRY_PASSWORD }}
      - name: push to radixdev
        run: |
          docker push radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
      - uses: azure/docker-login@v1
        with:
          login-server: radixprod.azurecr.io
          username: ${{ secrets.PROD_REGISTRY_USERNAME }}
          password: ${{ secrets.PROD_REGISTRY_PASSWORD }}
      - name: push to radixprod
        run: |
          docker push radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
  build-pipeline:
    name: Build-push-pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build pipeline
        run: |
          docker build . -f pipeline.Dockerfile -t radixdev.azurecr.io/radix-pipeline:${GITHUB_REF##*/}-latest -t radixprod.azurecr.io/radix-pipeline:${GITHUB_REF##*/}-latest
      - uses: azure/docker-login@v1
        with:
          login-server: radixdev.azurecr.io
          username: ${{ secrets.DEV_REGISTRY_USERNAME }}
          password: ${{ secrets.DEV_REGISTRY_PASSWORD }}
      - name: push to radixdev
        run: |
          docker push radixdev.azurecr.io/radix-pipeline:${GITHUB_REF##*/}-latest
      - uses: azure/docker-login@v1
        with:
          login-server: radixprod.azurecr.io
          username: ${{ secrets.PROD_REGISTRY_USERNAME }}
          password: ${{ secrets.PROD_REGISTRY_PASSWORD }}
      - name: push to radixprod
        run: |
          docker push radixprod.azurecr.io/radix-pipeline:${GITHUB_REF##*/}-latest