name: radix-operator-build
on:
  push:
    branches:
      - master
      - release
permissions:
  id-token: write
jobs:
  get-target-configs:
    name: Get target configs for branch
    outputs:
      target_configs: ${{ steps.get-target-configs.outputs.target_configs }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Get target configs
        id: get-target-configs
        run: |
          configs=$(ls $GITHUB_WORKSPACE/.github/workflows/config/${GITHUB_REF_NAME} | jq -Rsc '. / "\n" - [""]')
          echo ::set-output name=target_configs::${configs}

  build-deploy-operator:
    name: Build & push operator
    runs-on: ubuntu-20.04
    needs:
      - get-target-configs
    strategy:
      fail-fast: false
      matrix: 
        config: ${{ fromJson(needs.get-target-configs.outputs.target_configs) }}
    steps:
    - uses: actions/checkout@v2
    - name: Persist environment from ${{ matrix.config }} across steps
      run: |
        $GITHUB_WORKSPACE/.github/workflows/scripts/persist-env.sh

    - uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    
    - name: Build and push image
      run: |
        $GITHUB_WORKSPACE/.github/workflows/scripts/build-push-operator.sh

  build-deploy-pipeline:
    name: Build & push pipeline
    runs-on: ubuntu-20.04
    needs:
      - get-target-configs
    strategy:
      fail-fast: false
      matrix: 
        config: ${{ fromJson(needs.get-target-configs.outputs.target_configs) }}
    steps:
    - uses: actions/checkout@v2
    - name: Persist environment from ${{ matrix.config }} across steps
      run: |
        $GITHUB_WORKSPACE/.github/workflows/scripts/persist-env.sh

    - uses: azure/login@v1
      with:
        client-id: ${{ env.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.AZURE_TENANT_ID }}
        subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
    
    - name: Build and push image
      run: |
        $GITHUB_WORKSPACE/.github/workflows/scripts/build-push-pipeline.sh