name: radix-operator-pr
on:
  pull_request:
    branches:
    - master
    - 846-more-efficient-multistage-build
jobs:
  build-operator:
    name: Build-operator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build operator image
      env:
        REF: ${{ github. sha }}
        DOCKER_BUILDKIT: 1
      run: docker build -t radix-operator:${REF##*/} -f operator.Dockerfile .
  build-pipeline:
    name: Build-pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build pipeline image
      env:
        REF: ${{ github. sha }}
        DOCKER_BUILDKIT: 1
      run: docker build -t radix-operator:${REF##*/} -f pipeline.Dockerfile .