name: radix-operator-pr
on:
  pull_request:
    branches:
    - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install dependencies
        run: go mod download
      - name: Run Tests
        run: CGO_ENABLED=0 GOOS=linux go test `go list ./... | grep -v "pkg/client"` -timeout 2m

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.58.2

  verify-code-generation:
    name: Verify Code Generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Verify Code Generation
        run: |
          make verify-generate

  build-operator:
    name: Build-operator
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build operator image
      env:
        REF: ${{ github. sha }}
        DOCKER_BUILDKIT: 1
      run: docker build -t radix-operator:${REF##*/} -f operator.Dockerfile .

  build-pipeline:
    name: Build-pipeline
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build pipeline image
      env:
        REF: ${{ github. sha }}
        DOCKER_BUILDKIT: 1
      run: docker build -t radix-operator:${REF##*/} -f pipeline.Dockerfile .
