apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: radixapplications.radix.statoil.com
spec:
  group: radix.statoil.com
  version: v1
  names:
    kind: RadixApplication
    plural: radixapplications
    singular: radixapplication
    shortNames:
      - ra
  scope: Namespaced
