apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: radixregistrations.radix.equinor.com
spec:
  group: radix.equinor.com
  version: v1
  names:
    kind: RadixRegistration
    plural: radixregistrations
    singular: radixregistration
    shortNames:
      - rr
  scope: Namespaced
