apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: sampleapp
spec:
  environment:
    - name: dev
      authorization:
        - role: RadixReader
          groups:
          - "c6da402e-9426-4b27-ae22-a7432c3db31f"
    - name: qa
      authorization:
      - role: RadixReader
        groups:
        - "c6da402e-9426-4b27-ae22-a7432c3db31f"
    - name: prod
      authorization:
        - role: RadixReader
          groups:
          - "c6da402e-9426-4b27-ae22-a7432c3db31f"
  repository:
  cloneURL:
  sharedSecret:
  sshKey:
  defaultScript:
  secrets:
    test: "test"
    testing: "test2"
