apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: sampleapp
spec:
  environments:
    - name: dev
  components:
    - name: frontend
      src: src/frontend
      ports:
        - 80
        - 443
      public: true
    - name: backend
      src: src/backend
      ports:
        - 5000
