apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: sampleapp
spec:
  environments:
    - name: dev
      authorization:
      - role: RadixReader
        groups:
        - "c6da402e-9426-4b27-ae22-a7432c3db31f"
  components:
    - name: frontend
      src: src/frontend
      ports:
        - 80
        - 443
      public: true
    - name: backend
      src: src/backend
      ports:
        - 5000
  secrets:
    deployKey: "sample-sshKey"
    sharedSecret: "sample-GithubSecret"
